### ISSUE TITLE
Strange trackpad with latest release/commit and Interrupt Mode ELAN1200 V2.1.4

### ISSUE THREAD

**Issue by ghost** [VoodooI2C/VoodooI2C#150]
First thanks to all contributors of this project!
Using the latest commit/release, my trackpad works very strangely: cursor and gesture are getting stuck for about a second then they restarts working for about, another, second. The gestures feel like "incomplete", half done, and furthermore, the Dock crashes almost all times.
I tried every commit and I encountered these problems starting e3c9727efb77e6a9bfc2be09230837ef1eedd6cb.
I attached the logs of the Dock and a video documenting "unresponsiveness" 
Thanks in advance for support! 
[Archivio .zip](https://github.com/alexandred/VoodooI2C/files/2773342/Archivio.zip)
Right now I'm using Mojave, ELAN1200 (VoodooI2C 2.1.4 + I2CHID)

EDIT: 
I noticed using "Polling Mode" the trackpad works like a charm, but unfortunately and obviously kernel task takes up 9% of CPU, but It's, in my opinion, better than 70% taken by the interrupt when I use my trackpad. 
Thanks in advance for who will answer here, @alexandred @coolstar there is something to fix interrupt mode issues with this release? (with commits of November it's works even if I pin my device in order to use interrupt mode instead of polling mode)
My GPIO Pin is 0x55 and I have SunrisePoint-LP controller

**Comment by valinor61** [comment]
I had similar issue with that kext I undo all of my dsdt changes and put that SSDT on acpi/patched now it works well
[SSDT-XOSI.zip](https://github.com/alexandred/VoodooI2C/files/2776143/SSDT-XOSI.zip)

**Comment by giuligon** [comment]
@valinor61 Thanks a lot for answering and trying to provide a solution(previously I patched my DSDT applying the Windows10 Patch), but unfortunately I have the same issue unless I swap the newer version with an older one. Anyway, this problem seems to be related to Actuator and also to "Stuck finger fix"

**Comment by giuligon** [comment]
@muhammadasadbastomi Hi, yes I can help you! Please, in order to do this, report properly your problem with a copy of IOReg and attach your EFI Folder.

**Comment by alexandred** [comment]
Is this still an issue with the latest upstream?

**Comment by giuligon** [comment]
@alexandred Hi Alexander, thank you for answering, unfortunately I'm still facing the same issue !

**Comment by kprinssu** [comment]
Please use the latest version of VoodooI2C. Closing as there haven't been any responses in well over an year.
