### ISSUE TITLE
Touchpad buttons not working [Lenovo Y530]

### ISSUE THREAD

**Issue by somerfeld** [VoodooI2C/VoodooI2C#182]
Hi, I've got a problem with touchpad buttons. They are not working with this config: https://github.com/xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh/releases .
Touchpad works well with Multi-Touch.

**Comment by kprinssu** [comment]
Physical buttons (other than left click) is not supported. Please create a issue on VoodooInput to address this.
