### ISSUE TITLE
Touchpad buttons not working [Dell 5490]

### ISSUE THREAD

**Issue by CarretillaRoja** [VoodooI2C/VoodooI2C#186]
I have a Dell 5490 and, as many other Dell computers, the trackpad itself works perfectly, the gestures also work, but not the buttons. Is there anything can be made? I can provide whatever it takes in order to have it working. Thanks!

**Comment by msbence** [comment]
Dell 5400 have the issue as well

**Comment by kprinssu** [comment]
Physical buttons will not be supported within VoodooI2C. Please contact the dev team over at VoodooInput. We will need to create a mouse wrapper of sorts, closing for now.
