### ISSUE TITLE
Add palm rejection logic to touchpad satellites?

### ISSUE THREAD

**Issue by sunrez** [VoodooI2C/VoodooI2C#198]
Hi,

First thanks for this amazing work, I realize this feature request is a "nice to have" when a lot of core functionality is still being worked on...

Request:  Add some kind of palm rejection logic to the touchpad multi-touch logic.

Right now there is a 'mask time' which basically prevents touchpad inputs from being registered within some time-window of typing on the keyboard, but this is a bit too coarse.  I notice with just my hands/palms resting on the keyboard false inputs are registered.

Thinking about how to implement this, usually a palm inputs would appear like 'blobs' on the left+right side of the touchpad, not discrete fingers/circles on touchpad.  One could do a search on the radius of the touch (> than a threashold) and see if it intersects a 'bounding box' that's defined by upper left/right areas.

**Comment by sunrez** [comment]
Hi,

I have been thinking more about implementing this functionality and would like to take a stab at it.

Is there any diagnostics or way to visualize or display what the touchpad sees?  Something simple like a GUI window that shows dots of "touch" data?

**Comment by kprinssu** [comment]
This is not supported and probably will never will be as we directly interface VoodooInput which in turn sends the events to macOS. Please contact the dev team over at VoodooInput if you wish to implement this.

**Comment by JerryI** [comment]
It looks like that in 2.6 it works, kinda strange a bit. But in general, it rejects.
Lenovo Yoga 520
![Screenshot 2023-08-04 at 12 46 55](https://github.com/VoodooI2C/VoodooI2C/assets/4111822/4985429b-2899-43a9-953d-6b8da6719e15)

**Comment by kprinssu** [comment]
@JerryI Please do not post in a closed issue. As previously mentioned, this will never be supported.
