### ISSUE TITLE
Possible ways to customize stylus pen upper button and lower button

### ISSUE THREAD

**Issue by Jamesxxx1997** [VoodooI2C/VoodooI2C#204]
Hi , @blankmac.
I find a way to adjust the stylus pen lower button function via [bettertouchtool](https://youtu.be/7iLrBXLxEKo)

And I also find an app called [controllermate](https://www.orderedbytes.com/controllermate/) 
 , which might be able to adjust both upper button and lower button function , however , in a more complicated way.

Is there any other way to customize stylus pen buttons? Thank you.

**Comment by kprinssu** [comment]
Sorry, this is not supported. You will need to modify VoodooInput.

**Comment by NotMifa** [comment]
@Jamesxxx1997 how did you do it?

**Comment by kprinssu** [comment]
@NotMifa Please do not spam GitHub issues.
