### ISSUE TITLE
Double Click on my Touchpad

### ISSUE THREAD

**Issue by vincen5790** [VoodooI2C/VoodooI2C#220]
i just install mojave on Asus ROG GL553Vd FY280.. sometimes my touchpad was double click when i single click.. maybe bugs on the kext.. someone can fix the touchpad or the kext? thankyouu

**Comment by kprinssu** [comment]
Please use the latest version of VoodooI2C. Closing as there haven't been any responses in a while. Please create a new issue if you experience any issues.
