### ISSUE TITLE
Bugs with trackpad of Ideapad 330

### ISSUE THREAD

**Issue by TeijiW** [VoodooI2C/VoodooI2C#221]
I'm trying to enable my trackpad, but me and a community user who tried to help me think there is a bug in the project which causes the cursor to have the following bugs:

- Cursor "teleporting" when I'm moving in a direction
- Randomly the cursor stay "clicked" and don't stops more, just restarting my Notebook

I've tried VoodooIC2Synapatics modifications, but it didn't work

**Comment by ben9923** [comment]
Please attach a troubleshooting archive. We cannot guess what's wrong ;)

**Comment by juanaleixo** [comment]
Same problem, but stop "teleporting" when charging...

**Comment by ben9923** [comment]
> Same problem, but stop "teleporting" when charging...

@juanaleixo Are you using ACPIBatteryManager? It’s a known issue, try removing/replacing with SMCBatteryManager.

**Comment by kprinssu** [comment]
Please use the latest version of VoodooI2C. Closing as there haven't been any responses in a while. Please create a new issue if you experience any issues.
