### ISSUE TITLE
Issues with macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by Halelluja12** [VoodooI2C/VoodooI2C#308]
Seen voodooI2C new release not compatibility with Interrupt mode, but polling mode not working too, so sad

**Comment by kecinzer** [comment]
I'm on macOS 10.15.4 and both modes works fine :). You muset have something with your patches.

**Comment by Halelluja12** [comment]
> I'm on macOS 10.15.4 and both modes works fine :). You muset have something with your patches.

I have already GPIO patch,  override _OSI Mehtod patches, and modify _CRS Method, some case not working , i check with IO Reg, maclog VoodooI2C is work fine, but trackpad preferences panel still empty

**Comment by kprinssu** [comment]
@kecinzer Please don’t comment unless you have something constructive.  

@Halelluja12 please read https://voodooi2c.github.io/#Troubleshooting/Troubleshooting. Please follow those steps and then post a troubleshooting archive.

**Comment by kprinssu** [comment]
Closing as there has been no reply from @Halelluja12. Please reopen if you upload the troubleshooting archive.
