### ISSUE TITLE
Trackpad disable 2s on typing

### ISSUE THREAD

**Issue by nguyenduclong-ict** [VoodooI2C/VoodooI2C#311]
I install VoodooPs2Controller. All feature work but when i typing trackpad not working about 2s. How to using trackpad on typing? Example when i switch between two window with cmd + tab, trackpad delay!!
Thank!
Thinkpad t440s - Macos Mojave

**Comment by kprinssu** [comment]
This is a feature, you can disable this feature by going to the satellite kext and modifying the following value inside Info.plist:
`RM,deliverNotifications` to `false`

Line can be found here: https://github.com/VoodooI2C/VoodooI2CHID/blob/master/VoodooI2CHID/Info.plist#L103
