### ISSUE TITLE
Trackpad not working - Teclast F6 Pro  VooDooI2C  DSDT  TPDX  SYNA3602

### ISSUE THREAD

**Issue by Phoenil** [VoodooI2C/VoodooI2C#326]
Hello everyone! 

**Describe the bug**

The trackpad is being recognized by macO, but it doesn't work in any manner.

**Did you read the common errors documentation?**
Yes.

**Did you read the troubleshooting documentation?**
Yes.

**Have you searched the issue on Github, Gitter, or Google?**

I've searched and asked everywhere (such as Reddit, Hackintosh's Forums, Discord), this is my last hope.

**System Environment**

Operation System: macOs Mojave 10.14.6
Device Version: VoodooI2C + VoodooI2CHID (2.4.2)

**Troubleshooting Archive**
[Send me MacBook.zip](https://github.com/VoodooI2C/VoodooI2C/files/4677232/Send.me.MacBook.zip)
[MacBook ioreg.zip](https://github.com/VoodooI2C/VoodooI2C/files/4677234/MacBook.ioreg.zip)

**Additional context**
Nothing more to add! Feel free to ask!

**Comment by kprinssu** [comment]
Please I use the GitHub template.

**Comment by marianopela** [comment]
@Phoenil Are you sure you carefully read Documentation? You seem to be missing pins and proper return in your CRS method
![Screenshot 2020-05-28 at 23 08 51](https://user-images.githubusercontent.com/42821024/83194073-584e7a00-a138-11ea-93f5-cecc2448a383.png)

They surely are strange ACPIs, but you can give [Gpio Pinning](https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning) a try

**Comment by ben9923** [comment]
@Phoenil Please try removing the SYNA3602 personality from VoodooI2CHID's Info.plist.
Attach a new troubleshooting archive + IOReg.

**Comment by Phoenil** [comment]
@marianopela I'll take a look today at it

@ben9923 Done, 
[Send me MacBook.zip](https://github.com/VoodooI2C/VoodooI2C/files/4700952/Send.me.MacBook.zip)
[MacBook ioreg 3.zip](https://github.com/VoodooI2C/VoodooI2C/files/4700954/MacBook.ioreg.3.zip)

**Comment by kprinssu** [comment]
@Phoenil, as @marianopela pointed out, you _**need to**_ set up either interrupts or polling mode. VoodooI2C does not work out of the box, please read https://voodooi2c.github.io/#Polling%20Mode/Polling%20Mode.

Your DSDT shows that you a pin of 0x0, which is invalid. See, https://voodooi2c.github.io/#Polling%20Mode/Polling%20Mode and https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning

**Comment by Phoenil** [comment]
This is my unpatched DSDT 
![image](https://user-images.githubusercontent.com/6438222/83780274-410a1200-a68d-11ea-9084-65fb2610b48f.png)
[DSDT.aml-original.zip](https://github.com/VoodooI2C/VoodooI2C/files/4731256/DSDT.aml-original.zip)

**Comment by kprinssu** [comment]
@Phoenil and myself are carrying the discussion over on Gitter. Closing this for now.

**Comment by CrisHotpatch** [comment]
This is the solution:

https://www.tonymacx86.com/threads/voodooi2c-issues-syna3602.304029/post-2177566

**Comment by fmgdias** [comment]
SYNA3602 Trackpad - Solution

Show contents pkg on VoodooI2CHID.kext

Open Info.plist with PlistEditor Pro

In IOKitPersonalities: Rename VoodooI2CHIDSYNA3602Device to VoodooI2CHIDSYNA3602&Col2Device

IOClass: Rename VoodooI2CHIDSYNA3602Device to VoodooI2CHIDSYNA3602&Col2Device

IOPropertyMatch: Rename SYNA3602 To SYNA3602&Col2

If "&Col2" not work, try "&Col1"
