### ISSUE TITLE
Lenovo S145 - 15WIL - Problems with trackpad

### ISSUE THREAD

**Issue by prsolucoes** [VoodooI2C/VoodooI2C#329]
**Describe the bug**
Thanks for the great work.

1 - When i make login the trackpad is very slow for 10 seconds and after it move normal;
2 - When i drag something and leave the trackpad the object still dragged and i need click to it leave the object dragged (sometimes it happen and sometimes no);
3 - The third problem is when i click (pressing or touching) it click sometimes OK and on other it move the cursor for random place;

**Did you read the common errors documentation?**
YES

**Did you read the troubleshooting documentation?**
YES

**Have you searched the issue on Github, Gitter, or Google?**
YES

**System Environment**
Please answer:
1. What is your operating system? macos 10.15.5
2. What version of the drivers (including drivers) are you using? (latest - zip with all: https://www.dropbox.com/s/3vpebbc63u12rjf/EFI-FINAL.zip?dl=1)
3. What is your hardware configuration?  
1,99 GHz Quad-Core Intel Core i7
20gb ram 

**Troubleshooting Archive**
attahced
[MacBook Pro.zip](https://github.com/VoodooI2C/VoodooI2C/files/4707048/MacBook.Pro.zip)

**Additional context**
n/a

**Comment by kprinssu** [comment]
Can you please use an older version of VoodooI2C (<= 2.3) and report back.

**Comment by prsolucoes** [comment]
Sure, i will use version 2.2 and report here.

**Comment by kprinssu** [comment]
Please also try version 2.3.

**Comment by prsolucoes** [comment]
ok, i will use version 2.3 so

**Comment by prsolucoes** [comment]
Hi,

I have tested here and versions < 2.3 don't work in any place (boot, login and on desktop) - it stop totally. I need put external mouse to make cursor works again.

Only version 2.4 make it work again.

Thanks.

**Comment by djale** [comment]
Use VoodooI2C + VoodooI2CSynaptics  and make sure to edit synaptics kext info.plist

VoodooI2CSynaptics>Show Package Contents>Contents>info.plist
Edit IOPropertyMatch>name to "SYNA2B3C"

![65144776-95f7f080-da4a-11e9-8254-baa99d67fdcd](https://user-images.githubusercontent.com/29442362/83817810-040e4180-a6c6-11ea-8634-b76b685efd0f.png)

**Comment by prsolucoes** [comment]
> SYNA2B3C

Hi. It solve mt drag/drop problem. Now it is working nice. Only the TAP gesture that still failing...sometimes i need tap 4/5 times to the TAP/CLICK work.

And my trackpad is not showing more. Now it is searching for one.

![image](https://user-images.githubusercontent.com/395096/83839692-16db4300-a6d3-11ea-9523-65df8e5b50f2.png)

**Comment by djale** [comment]
You didn't patch your DSDT, later today I will send you a tutorial for everything related to Lenovo laptop build.

**Comment by kprinssu** [comment]
Thanks @djale. @prsolucoes this is no longer a VoodooI2C issue. Please get battery status working for preferences to properly work.

**Comment by prsolucoes** [comment]
@djale ok, please send to me :)
thanks more one time

**Comment by djale** [comment]
@prsolucoes https://github.com/djale/Lenovo-Hackintosh
