### ISSUE TITLE
Asus x510UR BQ292T GPI0 pin do not work

### ISSUE THREAD

**Issue by faruolo** [VoodooI2C/VoodooI2C#330]
Hello, im trying to make a SSDT patch according to the GPI0 pinning guide but none of the values works.

ive tried:

0x55
0x6d
0x41
0x81
0x17
0x1B
0x34

My touchpad works fine in polling mode, but ive spend all day trying to get it work in interrupt mode.

Im really sorry to ask for help, but i cannot find a solution anywhere.

Im attaching my DSDT and the SSDT patch i made.

[ELAN.zip](https://github.com/VoodooI2C/VoodooI2C/files/4731392/ELAN.zip)

**Comment by kprinssu** [comment]
Please follow the Github issue template and the feel re-open the ticket.
