### ISSUE TITLE
Lenovo Ideapad 330 SYNA2B49 Trackpad Kernel Panic

### ISSUE THREAD

**Issue by faruolo** [VoodooI2C/VoodooI2C#336]
**Describe the bug**
Kernel Panic after rename SBFI to SBFG

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. What is your operating system? 
MacOS Catalina 10.5.5
2. What version of the drivers (including drivers) are you using? VoodooI2C + VoodooI2CSynaptics 2.4.3
3. What is your hardware configuration?
Lenovo Ideapad 330 15 IKB 81FE
I5 8250U
12gb ddr4
480ssd

**Troubleshooting Archive**
[Troubleshooting.zip](https://github.com/VoodooI2C/VoodooI2C/files/4742793/Troubleshooting.zip)

**Additional context**
Described at the troubleshoot file.

**Comment by kprinssu** [comment]
You are using an invalid pin. Please use Gitter for help with pinning.
