### ISSUE TITLE
Touchpad not working with GPI0 SSDT

### ISSUE THREAD

**Issue by kecinzer** [VoodooI2C/VoodooI2C#337]
**Describe the bug**
My touchpad working fine in "XOSI" mode with rename _OSI to XOSI and this SSDT:

`DefinitionBlock ("", "SSDT", 2, "DRTNIA", "XOSI", 0x00001000)
{
    Method (XOSI, 1, NotSerialized)
    {
        Local0 = Package (0x11)
            {
                "Windows 2001", 
                "Windows 2001.1", 
                "Windows 2001 SP1", 
                "Windows 2001 SP2", 
                "Windows 2001 SP3", 
                "Windows 2006", 
                "Windows 2006 SP1", 
                "Windows 2009", 
                "Windows 2012", 
                "Windows 2013", 
                "Microsoft Windows NT", 
                "Microsoft Windows", 
                "Microsoft WindowsME: Millennium Edition"
            }
        If (_OSI ("Darwin"))
        {
            Return ((Ones != Match (Local0, MEQ, Arg0, MTR, Zero, Zero)))
        }
        Else
        {
            Return (_OSI (Arg0))
        }
    }
}`

But I want to switch from this mode to GPI0 according to this guide - https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad-methods/manual.html

I prepared this SSDT according my DSDT

![dsdt](https://user-images.githubusercontent.com/1541555/83992214-c6bce480-a94f-11ea-9db4-90682d2a9ba7.png)
`DefinitionBlock ("", "SSDT", 2, "hack", "I2C", 0x00000000)
{
    External (GPEN, FieldUnitObj)
    External (SBRG, FieldUnitObj)

    Scope (\)
    {
        If (_OSI ("Darwin"))
        {
            GPEN = One
            SBRG = One
        }
    }
}`

But touchpad doesn't work.

**Did you read the common errors documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Common%20Errors/Common%20Errors

YES

**Did you read the troubleshooting documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Troubleshooting/Troubleshooting.

YES

**Have you searched the issue on Github, Gitter, or Google?**
Please answer yes or no, this is to avoid creating duplicate Github issues.

YES

**System Environment**
Please answer:
1. What is your operating system?
macOS 10.15.5 (19F101)

2. What version of the drivers (including drivers) are you using?
VoodooI2C 2.4.3, Voodooinput 1.0.6

3. What is your hardware configuration?
Devicename: CPD0
IOName: ALP0017

**Troubleshooting Archive**
Here are IOReg screen with XOSI and GPI0 modes:

![XOSI](https://user-images.githubusercontent.com/1541555/83992145-8c534780-a94f-11ea-84ee-3132668f02e7.png)
![GPI0](https://user-images.githubusercontent.com/1541555/83992160-95441900-a94f-11ea-9cd3-a545d292a00a.png)

Can you please help me, what is wrong with GPI0 hack? Thank you.

**Comment by kprinssu** [comment]
Please use Gitter for pinning support. Github is mainly to fix issues with the code rather than getting help with configuration.
