### ISSUE TITLE
Ice Lake Intel I2C

### ISSUE THREAD

**Issue by MVDB0110** [VoodooI2C/VoodooI2C#342]
Do you have any idea, when Ice Lake will be supported in your kext? I see in the commits that a Ice Lake id is inserted in one of the plists, but there is no support in the kext for the controller.

**Comment by ben9923** [comment]
Which PCI ID does your device have?
If VoodooI2C doesn't have it, can you try manually adding it & installing the kext(s)?

**Comment by schwxr** [comment]
This may not be the case for you, but in my ICL build, VoodooI2C wouldn't load unless I applied the CML fix from #245 to my I2C controller. From there, I was able to proceed with my I2C device as usual.

**Comment by kprinssu** [comment]
@schwxr That fix has been added to upstream since 2.4 (March 2020), see https://github.com/VoodooI2C/VoodooI2C/commit/6d37695082eab4fd9d0203d3a46c7968f9c845d. Is there an underlying issue that has not been fixed?

@MVDB0110 ICL support should've been added with https://github.com/VoodooI2C/VoodooI2C/commit/c3bf644abb510bcc96d553c625ce469e4a2d95aa. As @ben9923 pointed out, do you perhaps have a controller that is not within that list?

**Comment by KhoraLee** [comment]
@kprinssu 6d37695082eab4fd95d0203d3a46c7968f9c845d This only fix CML laptops. ICL(Ice lake) Laptops also need same patch to use I2C Trackpad.

![Screen Shot 2020-08-10 at 6 21 47 PM](https://user-images.githubusercontent.com/18005062/89768275-5c364980-db36-11ea-91d3-73a9e5d17ce5.png)
And pci8086,34e9 is missing.

After fixing two issue 
![Screen Shot 2020-08-10 at 6 09 08 PM](https://user-images.githubusercontent.com/18005062/89768342-73753700-db36-11ea-8782-8d6f1598ae3f.png)
Trackpad works fine

**Comment by kprinssu** [comment]
Thanks @KhoraLee. Merged the changes into master.

**Comment by KhoraLee** [comment]
Now we need to figure out how to check ICL CPUs in order to apply this patch (6d37695082eab4fd95d0203d3a46c7968f9c845d) not only CML but also ICL.

**Comment by KhoraLee** [comment]
@kprinssu Please check this PR. I used same method to verify CPU. 

+It is working for me

**Comment by kprinssu** [comment]
@KhoraLee You want something like this for that if condition:
```
const char kIceLakeflag[2] = {'3', '4'};

if ( (tmp[0] == kCometLakeflag[0] && tmp[1] == kCometLakeflag[1] && tm[2] == kCometLakeflag[2]) || (tmp[0] == kIceLakeflag[0] && tmp[1] == kIceLakeflag[1])) {


.... 

```

**Comment by KhoraLee** [comment]
@kprinssu please check the pr #363.

**Comment by MVDB0110** [comment]
@KhoraLee Nice work! Sad that the fix will only work when a new version of VoodooI2C is released.

**Comment by kprinssu** [comment]
2.5 contains PR#363.
