### ISSUE TITLE
ELAN1300 doesn’t work on macOS Big Sur beta 2

### ISSUE THREAD

**Issue by OmerFlame** [VoodooI2C/VoodooI2C#346]
**Description of the issue**
VoodooI2C doesn’t inject correctly, only VoodooI2CServices and VoodooInput are being injected, the core and the satellite are not injected at all.

VoodooI2C worked in macOS Catalina perfectly, but not at all on Big Sur.

**Did you read the troubleshooting documentation?**
Yes.

**Have you searched the issue on Github, Gitter, or Google?**
Yes, I have asked on Gitter and have had countless hours of searching for fixes.

**System Environment**
1. I am using macOS Big Sur beta 2
2. I have the latest VoodooI2C and VoodooI2CHID from this repository.
3. I have an ASUS laptop, model X510UAR, with an ELAN1300 trackpad.

**Troubleshooting Archive**
I have tried my best, but all I can give are steps to reproduce.

1. Install macOS Big Sur beta 2 using OpenCore, and inject the kexts used above.

**Additional context**
I have already patched my DSDT using the Windows I2C and GPIO patches, nothing works.

**Comment by kprinssu** [comment]
Big Sur is not supported right now. However, it should be compatible as the underlying frameworks should not have  changed. 

I suspect you have some other issue with your configuration. Please use Gitter for support.
