### ISSUE TITLE
Can multiple satellites work at the same time?

### ISSUE THREAD

**Issue by im-bravo** [VoodooI2C/VoodooI2C#347]
Thank you very much for the excellent driver!

My computer has HIC touch screen and ELAN Clickpad.
I've successfully driven the touch screen by I2C.

I would like to know if the design supports multi satellites?

**Comment by kprinssu** [comment]
Multiple satellite kexts loading is not supported for the moment.

**Comment by coolstar** [comment]
@kprinssu multiple satellite kexts works fine. I have ELAN trackpad and Atmel touch screen on my netbook and it works fine

**Comment by kprinssu** [comment]
@coolstar You are right. @im-bravo you should be fine long as the VoodooI2CHID does not attach to the device.

**Comment by kprinssu** [comment]
@im-bravo I am closing this issue, please re-open if you cannot load multiple satellite kexts at the same time.

**Comment by im-bravo** [comment]
@coolstar @kprinssu Thanks for your information !!!
