### ISSUE TITLE
Trackpad stopped working after voodoo update

### ISSUE THREAD

**Issue by xrokz** [VoodooI2C/VoodooI2C#349]
**Describe the bug**
i wanted to update VoodooI2C to the latest version and the trackpad stopped working so i return to the one i have and its still not working.

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. What is your operating system? Catalina
2. What version of the drivers (including drivers) are you using? latest commit
3. What is your hardware configuration? I Don't know

**Comment by kprinssu** [comment]
@xrokz Please **_read_** the issue template. You have not provided any other information other than the driver not working.

First, please upload a troubleshooting archive and post your hardware configuration.
