### ISSUE TITLE
AUI165B work in GPIO model but only support two fingers gesture

### ISSUE THREAD

**Issue by ettingshausen** [VoodooI2C/VoodooI2C#351]
**Describe the bug**
Only two fingers gesture supported and there's no touchpad setting in system setting.

**Did you read the common errors documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Common%20Errors/Common%20Errors
yes

**Did you read the troubleshooting documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Troubleshooting/Troubleshooting.
yes

**Have you searched the issue on Github, Gitter, or Google?**
Please answer yes or no, this is to avoid creating duplicate Github issues.
yes

**System Environment**
Please answer:
1. What is your operating system? 
Catalina 10.15.6 (19G73)
2. What version of the drivers (including drivers) are you using?
VoodooI2C + VoodooI2CHID (2.4.3)
3. What is your hardware configuration?  

| Name     |           Model            | Note |
| :------- | :------------------------: | :--- |
| CPU      |    Intel Core i5 8250U     |      |
| GPU      |   Intel UHD Graphics 620   |      |
| RAM      |          8G + 4G           |      |
| SSD      | Samsung 970 EVO Plus 500G  |      |
| HDD      | Seagate ST1000LM035-1RK172 |      |
| WLAN     |          DW1820a           |      |
| TouchPad |          AUI165B           |      |

**Troubleshooting Archive**
Please attach the troubleshooting archive (as per https://voodooi2c.github.io/#Troubleshooting/Troubleshooting) and any additional logs or videos demonstrating the problem. Please attach any extra files to Github and *not* anywhere else like Google Drive.

[K43c-80-origin.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961031/K43c-80-origin.zip)
[k43c-80-IOReg.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961142/k43c-80-IOReg.zip)
[My patch SSDT-TPAD.aml.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961105/SSDT-TPAD.aml.zip)
[sys.log.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961246/sys.log.zip)

**Additional context**    

Two fingers gesture work fine and smooth, but no settings displayed.

**Comment by Goshin** [comment]
Seems you didn't load VoodooInput. Try adding it into your bootloader config.

**Comment by ettingshausen** [comment]
> Seems you didn't load VoodooInput. Try adding it into your bootloader config.
Sorry I can't get it, VoodooInput was contained in VoodooI2C,  extra boot args needed?
@Goshin

**Comment by Goshin** [comment]
What bootloader are you using?

**Comment by ettingshausen** [comment]
Clover

**Comment by ettingshausen** [comment]
After tried this patch   [SSDT-RMCF-Trackpad-enable.aml.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961408/SSDT-RMCF-Trackpad-enable.aml.zip)  
```
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20180427 (64-bit version)(RM)
 * Copyright (c) 2000 - 2018 Intel Corporation
 * 
 * Disassembling to non-symbolic legacy ASL operators
 *
 * Disassembly of iASL8ttynS.aml, Thu Jul 23 01:21:16 2020
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000078 (120)
 *     Revision         0x02
 *     Checksum         0xF9
 *     OEM ID           "hack"
 *     OEM Table ID     "RM-Track"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20180427 (538444839)
 */
DefinitionBlock ("", "SSDT", 2, "hack", "RM-Track", 0x00000000)
{
    External (_SB_.PCI0.LPCB.PS2K, DeviceObj)    // (from opcode)

    Scope (_SB.PCI0.LPCB.PS2K)
    {
        Name (RMCF, Package (0x02)
        {
            "Mouse", 
            Package (0x02)
            {
                "ActLikeTrackpad", 
                ">y"
            }
        })
    }
}
```
TouchPad Setting shown up but still only two fingers gesture .  
<img width="780" alt="Screen Shot 2020-07-23 at 1 17 56 AM" src="https://user-images.githubusercontent.com/9806325/88207570-92448400-cc82-11ea-9f57-f9d3a6855d82.png">

**Comment by Goshin** [comment]
Forget about it. Clover should load VoodooInput automatically.

**Comment by ettingshausen** [comment]
[k43c-80-after-SSDT-Patch.ioreg.zip](https://github.com/VoodooI2C/VoodooI2C/files/4961475/k43c-80-after-SSDT-Patch.ioreg.zip)

**Comment by Goshin** [comment]
> After tried this patch SSDT-RMCF-Trackpad-enable.aml.zip
TouchPad Setting shown up but still only two fingers gesture .

This means it is working in PS2 mode?

**Comment by ettingshausen** [comment]
>This means it is working in PS2 mode?  

It’s not possible, but it’s also a bit strange, I'm sure this is an I2C device.

**Comment by ettingshausen** [comment]
Is it the problem of ALPS? This is an ALPS touchpad.
I found @alexandred 's comment on [gitter](https://gitter.im/alexandred/VoodooI2C?at=5a4eb7b829ec6ac311bd31e2)
> actually there has never been alps support in voodooi2c
i do think it should be supported by a PS2 driver
its usual of dell to have dual PS/2 / I2C devices, its what i have and VoodooPS2 and VoodooI2C both work for me  

So ALPS should use VoodooPS2 instead？

**Comment by kprinssu** [comment]
@ettingshausen I have not heard of I2C based Alps touchpads (there are I2C based touchscreens by Alps). Best way to confirm is to check which driver loads in Windows or which kernel module in Linux.

**Comment by ettingshausen** [comment]
@kprinssu  There's no touchscreens devices on this laptop.  I just opened it and saw the touchpad chip, it is ALPS.  

![IMG_1464](https://user-images.githubusercontent.com/9806325/88575688-db2b7c80-d076-11ea-8978-d03fe68e0182.jpg)
 

Is it possible to fully work？Or I have to replace it with a Synaptics one.

**Comment by Goshin** [comment]
@ettingshausen try removing `VoodooPS2Mouse.kext` and `VoodooPS2Trackpad.kext` in `VoodooPS2Controller.kext/Contents/PlugIns`.

**Comment by ettingshausen** [comment]
I tried @coolstar 's [OS-X-ALPS-DRIVER](https://github.com/coolstar/OS-X-ALPS-DRIVER) still can't get it work.

**Comment by ettingshausen** [comment]
> @ettingshausen try removing `VoodooPS2Mouse.kext` and `VoodooPS2Trackpad.kext` in `VoodooPS2Controller.kext/Contents/PlugIns`.

I tried, but nothing has changed.

**Comment by Goshin** [comment]
mind providing the new IOReg file?

**Comment by ettingshausen** [comment]
[k43c-80.ioreg.zip](https://github.com/VoodooI2C/VoodooI2C/files/4983827/k43c-80.ioreg.zip)

**Comment by Goshin** [comment]
![image](https://user-images.githubusercontent.com/10056397/88578443-dea80f00-d048-11ea-82cc-ca653f21dcae.png)

I can see `IOHIDEventDriver` attached, instead of `VoodooI2CPrecisionTouchpadHIDEventDriver`.

**Comment by ettingshausen** [comment]
@Goshin Do you mean it recognized as a touchscreen device?

**Comment by blankmac** [comment]
If you look at the device usage pairs, it does not support the windows precision touchpad protocol but instead uses a vendor defined protocol for precision touch and is not supported by VoodooI2C for anything but simple mouse input.

**Comment by Goshin** [comment]
As @blankmac mentioned, the device doesn't support `0xD, 0x5` usage.

![image](https://user-images.githubusercontent.com/10056397/88580735-5cb9e500-d04c-11ea-96fe-9b7311fa21cf.png)

**Comment by ettingshausen** [comment]
Finally, I bought a ELAN online and replaced the ALPS one. 
It works like a charm. 

<img width="638" alt="2020-07-29 下午9 08 59" src="https://user-images.githubusercontent.com/9806325/88809656-f6b59500-d1e6-11ea-8dba-27f0ef9d6936.png">

Thank you guys! Love you 3000!
