### ISSUE TITLE
trackpad can't sense all fingers

### ISSUE THREAD

**Issue by xrokz** [VoodooI2C/VoodooI2C#352]
when i try to use my 4 fingers in trackpad it doesn't  work  and its only detect 2 fingers so i really need a fix 

this image i captured with [FingerMgmt app](https://github.com/jnordberg/FingerMgmt)
![image](https://user-images.githubusercontent.com/38587835/89133918-f12eb680-d528-11ea-8faf-1003de538bcc.png)

this is my archive:
[Send me xRokzs-MacBook-Pro.zip](https://github.com/VoodooI2C/VoodooI2C/files/5013088/Send.me.xRokzs-MacBook-Pro.zip)

**Comment by kprinssu** [comment]
For the last time, please stop creating multiple Github issues. Please use Gitter for configuration support.
