### ISSUE TITLE
Version cannot be updated

### ISSUE THREAD

**Issue by puzhengwu** [VoodooI2C/VoodooI2C#355]
Why is 2.1.4 still displayed when the version is updated to 2.4.3? Is it because the file name of the old version is not overwritten, other drivers can normally upgrade to the latest version

**Comment by kprinssu** [comment]
I am assuming you are referring to the satellite kexts? If so, yes this a known problem as their versions automatically are not updated when VoodooI2C is released.

**Comment by puzhengwu** [comment]
![image](https://user-images.githubusercontent.com/4401394/89614255-a01b1b80-d8b6-11ea-9a17-edbd536d605a.png)
hackintools

**Comment by kprinssu** [comment]
That is not an issue with VoodooI2C. That shows that you are using 2.1.4, Hackintool is warning there is a newer version out.

Closing as this is an user error.
