### ISSUE TITLE
Multi touch gestures not working on Big Sur

### ISSUE THREAD

**Issue by atzutz** [VoodooI2C/VoodooI2C#356]
ELAN1300 touchpad which worked on Catalina well using voodooi2c+Voodo2CHID, but on big sur multi touch gestures not working at all, using Opencore 0.6.0 and the latest VoodooI2C 2.4.6 kexts

**Comment by kprinssu** [comment]
Next time, please **_follow_** the Github issue template and  also **_read_** the troubleshooting documentation.

I suspect this is not a code issue. Please use Gitter for support.
