### ISSUE TITLE
Click+drag bug/problem with ELAN1200

### ISSUE THREAD

**Issue by okram24** [VoodooI2C/VoodooI2C#360]
I'm using VoodooI2C with VoodooI2CHID in OC kext folder, pinned with GPI0 0x1B. This is the problem I've encountered. A restart usually fixes the problem but sometimes it stays even after multiple reboots. Only after a period of time of computer inactivity does it go back to normal. I also have a HID touchscreen, maybe that's interfering.
[2020-08-10 15-02-51.mp4.zip](https://github.com/VoodooI2C/VoodooI2C/files/5051267/2020-08-10.15-02-51.mp4.zip)

**Comment by kprinssu** [comment]
Please use the Github issue template and re-open.
