### ISSUE TITLE
The touchpad Dell Vostro 3590 stops working after 2-3 system reboots

### ISSUE THREAD

**Issue by vannadium1788** [VoodooI2C/VoodooI2C#374]
There is a Dell vostro 3590-8914 laptop with Big Sur 11.0 beta 5 + opencore 0.6.0 installed

The problem is this: When the system starts, the touchpad performs its minimum functions (cursor, Left-Click, Right-Click) in the settings the trackpad is not detected
However, after 2-3 reboots (and maybe more), the touchpad begins to fully function, the trackpad appears in the settings and all gestures work
There was a similar problem on Catalina 10.15.6
And on Big Sur 11.0 the situation has not changed

How to fix this bug?

I use voodooi2c, voodooi2CHID 2.4.4

**Comment by kprinssu** [comment]
Please re-open after you have read the troubleshooting documentation and the properly filled out the Github issue template.
