### ISSUE TITLE
Lenovo Ideapad S145-15IIL Touchpad Left Click not working on Catalina

### ISSUE THREAD

**Issue by Pablitus** [VoodooI2C/VoodooI2C#376]
I have the Ideapad S145-15IIL Ice Lake Laptop with the ELAN touchpad and with the VoodooI2CELAN 2.4.4 the trackpad works, but the right click is not working...i need to use an external mouse to have proper clicks

**Comment by Kmbeatz** [comment]
Can you share the OC Folder?

**Comment by Pablitus** [comment]
> Can you share the OC Folder?

Sure
[OC.zip](https://github.com/VoodooI2C/VoodooI2C/files/5198290/OC.zip)

**Comment by kprinssu** [comment]
Please read the troubleshooting guide and fill out the Github issue template.

Additionally, if this a physical button then please raise a ticket within VoodooInput.
