### ISSUE TITLE
GPIO Pinning on IceLake

### ISSUE THREAD

**Issue by Paolo7297** [VoodooI2C/VoodooI2C#377]
Hello! I'm trying to do gpio pinning on icelake (polling mode was working, but double tap to drag is not working well and i use it a lot), i found my APIC pin is 0x35, so i checked here: https://github.com/coreboot/coreboot/blob/master/src/soc/intel/icelake/include/soc/gpio_defs.h
And noticed that i have two alternatives: B21 and D13.
Starting with this i checked here:
https://github.com/coreboot/coreboot/blob/master/src/soc/intel/icelake/include/soc/gpio_soc_defs.h
and found: 29 and 95.
I found here: http://sbexr.rabexc.org/latest/sources/7c/4a03585eb0d804.html
communities for pins and ended with:
53 (0x35) and 140 (0x8C).
I tried both but they aren't working...
I tried also 0x17, 0x1B, 0x34 and 0x55 as suggested in the guide, but none of them is working...
What can i do?

This is my patched DSDT:
[DSDT.aml.zip](https://github.com/VoodooI2C/VoodooI2C/files/5198170/DSDT.aml.zip)

**Comment by kprinssu** [comment]
Please use Gitter for support with configuration and initial set up.
