### ISSUE TITLE
Worked on Catalina but not in Big Sur beta

### ISSUE THREAD

**Issue by seungjunProgramming** [VoodooI2C/VoodooI2C#378]
**Describe the bug**
I use Liteon's touchpad and it worked on Catalina Using Clover.
But I installed VoodooI2C + VoodooI2CHID on Big Sur using Opencore, it doesn't work

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system? Big Sur beta6
2. What version of the drivers (including drivers) are you using? 2.4.4
3. What is your hardware configuration?Liteon touchpad (TPD0) -> the maker of the laptop refuses to tell me the model

**Troubleshooting Archive**
![Screen Shot 2020-09-11 at 7 50 40 PM](https://user-images.githubusercontent.com/64799763/92916020-15ef4580-f468-11ea-8e75-2c2e142daaa4.png)

There are no errors related to voodooi2c but 1 at ApleIntelLpssl2C.kext
Somebody told me to block ApleIntelLpssl2C.kext, but how can I block it???

**Additional context**

**Comment by ben9923** [comment]
A screenshot of IOReg is not helpful. The issue template suggests what you should attach for debugging (ACPI, an actual copy of IOReg, kernel logs).

There's no need to block Apple's I2C kexts.

**Comment by kprinssu** [comment]
As @ben9923 please fill out the issue template and attach a troubleshooting archive. Please re-open the Github issue once you have done so.
