### ISSUE TITLE
Invalid report(0)

### ISSUE THREAD

**Issue by nikhil19rathore99** [VoodooI2C/VoodooI2C#380]
**Describe the bug**

**Did you read the common errors documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Common%20Errors/Common%20Errors

**Did you read the troubleshooting documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Troubleshooting/Troubleshooting.

**Have you searched the issue on Github, Gitter, or Google?**
Please answer yes or no, this is to avoid creating duplicate Github issues.

**System Environment**
Please answer:
1. What is your operating system? 
2. What version of the drivers (including drivers) are you using?
3. What is your hardware configuration?

**Troubleshooting Archive**
Please attach the troubleshooting archive (as per https://voodooi2c.github.io/#Troubleshooting/Troubleshooting) and any additional logs or videos demonstrating the problem. Please attach any extra files to Github and *not* anywhere else like Google Drive.

**Additional context**
![Screenshot 2020-09-16 at 3 17 32 PM](https://user-images.githubusercontent.com/32436513/93321412-bf9b5180-f82f-11ea-996a-119735ce790b.png)
After  waking up from sleep trackpad won't work
OS: 10.15.6
Clover: 5122
trackpad: voodooi2c FTE 2.4.4
Asus X556UQK

**Comment by kprinssu** [comment]
Please re-open after you have attached a troubleshooting archive. It also sounds similar to the issue you had earlier on the year, https://github.com/VoodooI2C/VoodooI2C/issues/305.

Please double check your configuration before re-opening and creating new tickets.
