### ISSUE TITLE
Switch to Acidanthera MacKernelSDK

### ISSUE THREAD

**Issue by vit9696** [VoodooI2C/VoodooI2C#383]
Hello, we made a new product designed to help all the kext developers to easily target different macOS versions — [MacKernelSDK](https://github.com/acidanthera/MacKernelSDK). This is a modified Kernel.framework SDK, which contains private headers, removed deprecations, availability checks in many places, and several other fixes.

In Acidanthera we migrated all our kexts to use MacKernelSDK including VoodooInput. Perhaps it will be useful for VoodooI2C as well. Feel free to adopt or even contribute.

**Comment by kprinssu** [comment]
I am looking at the changes in VoodooInput (https://github.com/acidanthera/VoodooInput/commit/c3f635221ffbeda788b28568dce733d91d0a8a10) and it looks like a drop-in replacement for Apple provided SDK,

If so, this should be a realtively easy change on my end, however I do not exactly have a I2C device that I can test with.

**Comment by kprinssu** [comment]
Implemented with https://github.com/VoodooI2C/VoodooI2C/pull/420.
