### ISSUE TITLE
keyboard Prtsc can't disable touch pad

### ISSUE THREAD

**Issue by laozhiang** [VoodooI2C/VoodooI2C#387]
update voodooi2c form 2.4.2 to 2.5.   boot with Opencore 0.6.1 ,VoodooI2C.kext, voodooI2CHID.kext and VoodooPS2Controller.kext(2.1.6) 
When use 2.4.2, It can disable touch pad by press key 'Prtsc',  but is no work in 2.5

**Comment by kprinssu** [comment]
Please fill out the Github issue template.

This also sounds like a configuration issue, please use Fitter.
