### ISSUE TITLE
Touchpad stopped working after upgrading to Clover 5123 (5124)

### ISSUE THREAD

**Issue by DmitriySU** [VoodooI2C/VoodooI2C#394]
Hey. My ELAN 1200 has been successfully running on an Asus laptop for over a year. But with the transition to Clover 5123 and 5124, the ETPD device does not cling to IOReg. The touchpad stopped working. I return Clover 5122 - everything works. Drivers and kexts are the same. How to fix?
Thanks.

**Comment by kprinssu** [comment]
Please read the troubleshooting documentation and **read and fill out** the Github issue template.
