### ISSUE TITLE
VoodooI2C.kext and VoodooI2CHID.kext are not working on Clover 5125

### ISSUE THREAD

**Issue by androidxda23** [VoodooI2C/VoodooI2C#395]
When I update my Clover version to 5125 , The kext didn’t work

**Comment by mbppereira** [comment]
same here! the same kext works with OC, but with clover 5125 not.

**Comment by kprinssu** [comment]
Clover is not what it used to be. It is not getting frequent updates and the issue is most likely within how the kexts are loaded by Clover.

Please contact the Clover developers for support as this is most likely not an issue VoodooI2C.
