### ISSUE TITLE
[IceLake] Dell Vostro 5401 - i7 1065G7, lagging trackpad

### ISSUE THREAD

**Issue by dreamwhite** [VoodooI2C/VoodooI2C#397]
Hi there,
I'm opening this issue for @Lorys89 since he's busy.
He has bought a Dell Vostro 5401 - i7 1065G7 and we hadn't found a way to fix the lagging trackpad.
It's trackpad BIOS name is `_SB.PCI0.I2C1.TPD0` and both with Interrupt and with Polling mode, the trackpad lags.
Here you are a zip containing both the EFI and a copy of his IORegistry: 
[Dell Vostro 5401 - i7 1065G7.zip](https://github.com/VoodooI2C/VoodooI2C/files/5487604/Dell.Vostro.5401.-.i7.1065G7.zip)

There isn't any custom bus speed config specified, nor any modified version of the kexts.
Do you have any idea? 
TIA

**Comment by kprinssu** [comment]
Please read the troubleshooting guide and fill out the Github template.

I suggest you reach out for help on Gitter before re-opening this ticket.
