### ISSUE TITLE
Trackpad not showing in preferences

### ISSUE THREAD

**Issue by pascalbrennich** [VoodooI2C/VoodooI2C#402]
TPD0 touchpad via HID Interface working but not showing up in preferences "Trackpad"
can't make a primary Click because of force touch emulation...
In preferences i could select tap to click i think, if it would show up.

Anyone help please?

**Comment by kprinssu** [comment]
Please look at existing issues. If you did read the Github issue template and searched you would've found that you need to get battery status working.
