### ISSUE TITLE
Desktop picture on trackpad :)

### ISSUE THREAD

**Issue by Ukr55** [VoodooI2C/VoodooI2C#403]
Hi, I have issue with ELAN trackpad ASUS ZenBook 15 UX534.
Desktop picture shown on my trackpad, very strange and amazing ))
And yes this is trackpad on asus notebook.
macOS Catalina do not have this issue but trackpad does not working.
![photo_2020-11-14 16 47 29](https://user-images.githubusercontent.com/18126167/99150157-45564480-269b-11eb-81d8-0003cb27dde3.jpeg)

**Comment by kprinssu** [comment]
Please use Gitter for configuration support.
