### ISSUE TITLE
Panic while attaching to I2C0 (8086; a368)

### ISSUE THREAD

**Issue by williambj1** [VoodooI2C/VoodooI2C#405]
**Describe the bug**
This panic existed a long time ago, I always deleted `A368` in Info.plist to avoid it. However, after #370 was merged, devices are matched using `IOPCIMatch` so the panic is basically unavoidable.

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. What is your operating system?
   macOS Big Sur 11.0.1 (20B29) & macOS Catalina 10.15.7 (19H2)
2. What version of the drivers (including drivers) are you using?
   v2.5.2 from GitHub Release
3. What is your hardware configuration?
   - Intel Core i7 8750H (Coffee Lake)
   - Trackpad: ELAN1404 polling mode (Asus Laptop)
   - ANX7411 on I2C0 (a368), it's a USB-C controller

**Troubleshooting Archive**
[Archive.zip](https://github.com/VoodooI2C/VoodooI2C/files/5544072/Archive.zip)

**Comment by startpenghubingzhou** [comment]
Using atos  I got this message:
```
getMatchedName(IOService*) (in VoodooI2C) + 38
```

Seems that `getMatchedName` function returned a NULL pointer when is being executed.

For now I thought two solution: add  a  NULL pointer check in this function simply , or check the NULL name and add one. In  my opinion, I think the first way may be a best solution.
