### ISSUE TITLE
Dell e7280 Trackpad not working, Cannot apply GPIO or I2C controller enable patches

### ISSUE THREAD

**Issue by takobaba** [VoodooI2C/VoodooI2C#407]
**Describe the bug**
Dell E7280 Intel i5 7300U trackpad doesn't work. Open Core 0.6.3 with voodooi2c and voodooi2chid kexts are loaded.

I cannot apply the GPIO controller patch to DSDT it is greyed out on maciasl. 

Maciasl version: 

/Applications/MaciASL.app/Contents/MacOS/iasl-stable -v

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200925
Copyright (c) 2000 - 2020 Intel Corporation

**Did you read the common errors documentation?**
Yes; 
Could not find GPIO controller - The GPIO controller enable patch has not been applied.
GPIO controller enable patch cannot be applied on maciasl
please check the below screenshot. 
![image](https://user-images.githubusercontent.com/3728072/99861828-b477ef80-2beb-11eb-93a8-6a2615b78a9c.png)
I2C controller patch also cannot be applied. 

**Did you read the troubleshooting documentation?**
Yes

[Machine Details - IOREG.zip](https://github.com/VoodooI2C/VoodooI2C/files/5576719/Machine.Details.-.IOREG.zip)
[Trackpad Logs.txt](https://github.com/VoodooI2C/VoodooI2C/files/5576722/Trackpad.Logs.txt)

**Have you searched the issue on Github, Gitter, or Google?**
Yes, couldnt find much information tried many ways none of them worked

**System Environment**
Please answer:
1. What is your operating system? 
MacOS Catalina 10.15.7 upgraded from mojave
2. What version of the drivers (including drivers) are you using?
2.5.2 Voodooi2c and voodooi2cHID
3. What is your hardware configuration?
Dell e7280
intel i5 7300U
HD620 GPU

**Additional context**
I cannot apply the GPIO patch for some reason that might be causing the issue.

I have XOSI enabled.
Trackpad is not recognized by mac.

All the logs are attached.

**Comment by kprinssu** [comment]
This is clearly a configuration question. Please use Gitter for support.
