### ISSUE TITLE
Disable empty I2C devices + TPS65988 device?

### ISSUE THREAD

**Issue by antoniomcr96** [VoodooI2C/VoodooI2C#408]
Some laptops, like mine, have I2C platforms which are designed to be linked to devices that are not necessarily built-in in the configuration of all models.

For example I have a:
`I2C0` device that should connect a `NFC1` device, that normally isn't available in my laptop (only in custom configurations);
`I2C1` device that should connect a `TPL0`, that I don't have (instead I have a normal trackpad that works with VoodooPS2Controller);

![image](https://user-images.githubusercontent.com/63928525/99985781-ae7e3c00-2dae-11eb-9bb7-34f7cffbac6f.png)
IOReg shows that the driver is correctly loaded, but isn't linked to any device in both I2C.

I think that it could be a good idea to set the I2C devices that don't connect to any device (like these two) in a low power mode in order to be more battery-friend. I don't know if the driver already does this work and if it is actually possible/a good idea.

The other question is about a TPS65988 device (its name in windows/ PDFW here in IOReg) that seems to be recognized by VoodooI2C. I asked in gitter for some info about but it seems that no one knows about it.
![image](https://user-images.githubusercontent.com/63928525/99986391-6b709880-2daf-11eb-894b-1ba5a9271e25.png)
It is only activated if I patch `OSYS`. It looks like [it has something to do with USBc power management](https://www.ti.com/product/TPS65988). Does VoodooI2C handle it correctly or is it better to deactivate it (=don't patch OSYS).

(I use the driver for the HID touchscreen with pen that works well)

Thanks in advance. I hope this could be useful also for other users.

**Comment by kprinssu** [comment]
It looks like you do not have any supported I2C devices. You probably have a non-standard ACPI device and your device may not actually be I2C based and you should disable any unsupported devices with your DSDT by returning 0 within the _STA method.
