### ISSUE TITLE
Trackpad buttons not working while not touching the trackpad's touch area.

### ISSUE THREAD

**Issue by valinor61** [VoodooI2C/VoodooI2C#409]
**Describe the bug**
Dedicated physical trackpad buttons are not working while not touching the trackpad's touch area.

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
macOS Big Sur 11.0.1
VoodooI2C ver2.5.2
ELAN 1200

I guess the issue is known for a long time. I can't use dedicated physical buttons for just clicking or right-clicking.

**Additional context**
I asked about this issue in gitter according to the response I get, with an additional controller for dedicated physical buttons this issue can be fixed.

**Comment by kprinssu** [comment]
Next time, please use Gitter for support regarding configuration such as this and also please thoroughly read the support documentation and properly fill in the Github issue template.

Dedicated buttons are not supported, neither are "zones".
