### ISSUE TITLE
Building VoodooI2C kext error

### ISSUE THREAD

**Issue by yvelta1** [VoodooI2C/VoodooI2C#410]
I have comet lake laptop. and my touchpad starts working when I go to sleep mode, and leave the sleep mode.
So I decided to change voodooi2cpcicontroller.cpp.

[(screenshot file)](https://imgur.com/a/cQ3rI0B)

And started to build.

..And error occurred. [(Screenshot)](https://imgur.com/a/HAuvhgb) so I downloaded voodooinput and copied to the folder.

and twice error occurred. ([Screenshot)](https://imgur.com/a/MRORaxC)

what should I do?

**Comment by kprinssu** [comment]
Please read the documentation on how to build the kext.
