### ISSUE TITLE
Unable to work with Elan 1300

### ISSUE THREAD

**Issue by yuvrajharod** [VoodooI2C/VoodooI2C#411]
Here's my EFI folder and unfortunately I've tried all the kexts and DSDTs but still not working.

Here's a link to my EFI folder: https://drive.google.com/file/d/1zTDs_ktenwR8cbAu6XBsmnmbIkpwx0iY/view?usp=sharing

**Comment by yuvrajharod** [comment]
I've a laptop from asus with a I2c Trackpad Elan 1300 and this one's unfortunately not working with me

**Comment by kprinssu** [comment]
Please use Gitter for support with configuration. Next time, please read and fill in the Github issue template.
