### ISSUE TITLE
Elan 1300 not working on Asus laptop

### ISSUE THREAD

**Issue by yuvrajharod** [VoodooI2C/VoodooI2C#412]
Trackpad not working on Asus laptop

I've read the common errors doc but doesn't seem to work in my case

Also went through the trouble shooting doc and tried all what I can do but no luck :(

I've already googled it and read on github reddit and other platforms. All of them gave different kexts and methods but they could work for me. I tried using all the patchs _osi and other but none of them were showing any sign of working.

 I'm currently using macOS bigsur 11.0.1 
I've got an I2c Trackpad, I've tried using VoodooI2c, VoodooI2cHID, VoodooI2cElan and AppleInput kexts.
I've got a laptop, Asus Vivobook S510UN-BQ052T. 
i7-8550u 2.0Ghz
16Gb Ram 
250GB SSD from WD
1TB HDD(Windows installed)
Intel 620 
MX150 GPU
PS2 Keyboard
I2c HID Mouse

So finally to sum up. I have the mentioned laptop with Elan 1300 Trackpad and I'm unable to make my trackpad work. This is really important for me is the reason I m spending so much time to make it work. I've tried kexts used by other people for the same trackpad but different laptop. I've tried different versions of kexts used by similar laptops, yet no results. I tried to contact someone who had really great info about this and has one same trackpad working in his Asus laptop but he could work it out and suggested me this and hence I m asking the platform for the help if you can....

Thanks for reading and your time in advance

I'm also attaching a copy of my EFI folder for better assessment
[EFI.zip](https://github.com/VoodooI2C/VoodooI2C/files/5612194/EFI.zip)

**Comment by kprinssu** [comment]
As previously mentioned, please use Gitter https://github.com/VoodooI2C/VoodooI2C/issues/411.
