### ISSUE TITLE
Can we have one finger scroll with touchscreen? Like what linux touchscreens do.

### ISSUE THREAD

**Issue by kingo132** [VoodooI2C/VoodooI2C#424]
I can scroll the content in Linux using one finger to touch the screen.
In mac os, with VoodooI2C, I need to touch two fingers on the screen to scroll the content.
So I'm wondering how can I make it to scroll the content by just touch one finger on the screen in mac os. Are there any clues about how to do this? Which part of the code can I modify to achieve this? Thanks!

**Comment by kprinssu** [comment]
Sorry, but this is not possible as macOS does not support this. We emulate a Magic Trackpad so any capability or configuration not supported by it is not supported by us.
