### ISSUE TITLE
Problem with 2.6.3 and airdrop after opening lid.

### ISSUE THREAD

**Issue by Mateo1234454545** [VoodooI2C/VoodooI2C#429]
With latest release 2.6.3 wifi is turned off when closing lid, so when waking ,wifi needs 1-2sec to reconnect and airdrop is disabled (need to enable it manual). If I just put laptop to sleep from menu everything is OK.

With release 2.6.2 (and all previous) that doesn't happen.

I use BROADCOM BCM94360CS2.

**Comment by kprinssu** [comment]
Kindly stop posting here.
