### ISSUE TITLE
Sony Vaio FE15 VJFE52 trackpad not working

### ISSUE THREAD

**Issue by pdevonie** [VoodooI2C/VoodooI2C#430]
Sony Vaio FE15 VJFE52

i5 10210u
Trackpad: SYNA3602

I asked Maldon for help, but we couldn't get his trackpad to work, can you help me? He gives none of life;

Sending send_me and ioreg with the DSDT made by Maldon and without the ssdt.
https://drive.google.com/drive/folders/1ZtFOATY5OL0KThQKFlBILguUjkig7tQy?usp=sharing

**Comment by kprinssu** [comment]
This is most likely a configuration issue, please use Gitter for support. Next time, you should read the troubleshooting documents and fill in the Github issue template.
