### ISSUE TITLE
Coffee lake  cannonlakeH gpio issues 

### ISSUE THREAD

**Issue by moonmouse1111** [VoodooI2C/VoodooI2C#431]
![16106520397665296081537439170022](https://user-images.githubusercontent.com/77461036/104638081-9a173b00-569d-11eb-8a6e-5243002b1515.jpg)

Hackintosh 
Stuck on loading gpio data, what can I do?

**Comment by kprinssu** [comment]
As the Github issue template mentions, please read the troubleshooting documents and fill it in. As this is most likely a configuration issue, please Gitter for support.
