### ISSUE TITLE
Possible AppleACPIPlatform support for i2c batteries?

### ISSUE THREAD

**Issue by Kethen** [VoodooI2C/VoodooI2C#432]
for example, the acer switch 11v
```
    Scope (_SB.PCI0.I2C1)
    {
        Device (BAT1)
        {
            Name (_HID, EisaId ("PNP0C0A") /* Control Method Battery */)  // _HID: Hardware ID
            Name (_UID, One)  // _UID: Unique ID
            Name (_DEP, Package (0x01)  // _DEP: Dependencies
            {
                I2C1
            })
...
```
[DSDT.dsl.txt](https://github.com/VoodooI2C/VoodooI2C/files/5880544/DSDT.dsl.txt)
With SMCBatteryManager, AppleACPIPlatform would attempt to access i2c1, possibly with apple's i2c implementation, with voodooi2c loaded this results in
```
[  128.824210]: ACPI Error: ACPI Error: Region GenericSerialBus (ID=9) has no handlerRegion GenericSerialBus (ID=9) has no handler (20160930/exfldio-392)
[  128.824228]:  (20160930/exfldio-392)
[  128.824239]: [ECNR] @0001A #0070:  [ECNR] @0001A #0070:  II22CCWW =  = EECCWWRR /* External reference */ /* External reference */
```
since serial communication with BAT1 is already programmed in the DSDT, is it possible to have a device nub driver that is AppleACPIPlatform compatible?

**Comment by kprinssu** [comment]
I also have not seen the above ACPI error before and you are best to contact SMC Battery Manager devs (acidanthera). It may very be possible that that device may not even be a battery device.

Assuming that the battery is actually reporting via I2C, your best bet is for you to create a satellite kext that uses VoodooI2C for the I/O and set up the necessary battery reporting. I have not heard of battery devices reporting via I2C. There is also another gotcha here, VoodooI2C is mainly geared towards input devices and not specifically for battery reporting so this will be uncharted territory. 


This will also be outside of scope of our current project and we will not be implementing ourselves, however, you are welcome to do so.
