### ISSUE TITLE
The touchpad loses my fingers while they are on touchpad

### ISSUE THREAD

**Issue by kdmitrienko** [VoodooI2C/VoodooI2C#434]
**Describe the bug**
Gpio mode.

I recorded 2 videos with FingerMgmt to make it clearer:

Normal work - https://user-images.githubusercontent.com/78313013/106462215-a3005e80-644a-11eb-9857-c7aae268599b.mov
Bug work (splitted in 2 videos due to 10 mb max files size):
1 - https://user-images.githubusercontent.com/78313013/106462893-83b60100-644b-11eb-83e2-12c7beff8dee.mov
2 - https://user-images.githubusercontent.com/78313013/106462944-96303a80-644b-11eb-9cb3-712a53dac1bf.mov

In the first video (normal operation) - I move my finger over the touchpad without lifting my finger from the touchpad and everything is fine.
In the second and third videos - I move my finger along the touchpad without lifting my finger from the touchpad, but in FingerMgmt you can see that the touchpad registers as if I constantly lift my finger from the touchpad. Although I don't really do it.

The bug appears randomly. It lasts for 10-30 seconds and then disappears.

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. 10.15.7 (19H2)
2. 2.6.3
3. Asus Zenbook UX410UFR (Core i5-8250u, uhd 620)

**Troubleshooting Archive**
[flashing.zip](https://github.com/VoodooI2C/VoodooI2C/files/5904133/flashing.zip)

**Additional context**
This bug is not reproduced on Ubuntu and Windows 10.

**Comment by kprinssu** [comment]
Please only have one ticket open. It is most likely a polling issue.
