### ISSUE TITLE
Touchpad not working HP Envy x360 13-ar0014nw

### ISSUE THREAD

**Issue by snakus** [VoodooI2C/VoodooI2C#439]
I2C doesn;t detects touchpad.
Here's my efi folder http://www.mediafire.com/file/e17g6m78nbpkrhg/EFI.zip/file
System log and aida log in attachments
[aida.txt](https://github.com/VoodooI2C/VoodooI2C/files/5956743/aida.txt)
[systemlog.txt](https://github.com/VoodooI2C/VoodooI2C/files/5956746/systemlog.txt)
[bootlog.txt](https://github.com/VoodooI2C/VoodooI2C/files/5956750/bootlog.txt)

**Comment by kprinssu** [comment]
You most likely have to configure your GPIO pin or enable polling mode. Please read the doucmentation here, https://voodooi2c.github.io and next time fill in the Github issue template as you didn't even upload the IO Reigstry dump.

If you need help setting this up, please use Gitter.
