### ISSUE TITLE
[Not really an issue] Force-touch emulation

### ISSUE THREAD

**Issue by CharlieJiangXXX** [VoodooI2C/VoodooI2C#441]
I am sorry if this seems out-of-the-place. I am just wondering if the force-touch could be implemented like the iOS Haptic Touch. For instance, when the touchpad is clicked continuously for, say, 2 seconds, VoodooI2C will tell macOS that the user has just evoked a force-touch incident. From my point of view, I think this is feasible. I will close this if it is not in the right place.

**Comment by kprinssu** [comment]
Please raise this issue upstream VoodooInput which is managed by @acidanthera.
