### ISSUE TITLE
Please increase VoodooI2CFTE tracking speed

### ISSUE THREAD

**Issue by bankerza123** [VoodooI2C/VoodooI2C#448]
My trackpad is FTE1001 it worked but tracking speed is so slow
i used max value in trackpad prefpane but so slow, please fix this

**Comment by kprinssu** [comment]
You can change the tracking speed by using Trackpad setting within System Preferences.

If you do not have it, then you most likely do not have multitouch using. If that is the case please use Gitter and request for support there.
