### ISSUE TITLE
yoga 500 skylake IOname pci8086,9d31

### ISSUE THREAD

**Issue by GxHERO** [VoodooI2C/VoodooI2C#454]
I activate my device touchscreen but dont work multitouch so need help.

What types of data or files should I share to get your support?

[IOreg pic](https://i.ibb.co/SnK4GzG/Ekran-Resmi-2021-05-04-12-30-43.png)

\_SB.PCI0.I2C0.SHUB

pci8086,9d31

**Comment by kprinssu** [comment]
Please use Gitter for support as you most likely need help with setting up your configuration.
