### ISSUE TITLE
Laggy input

### ISSUE THREAD

**Issue by tmbt78** [VoodooI2C/VoodooI2C#456]
**Describe the bug**
Timeout waiting for device to complete host initiated reset OR laggy input on touchpad and perfectly working touchscreen

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes. Could be something similar to https://github.com/VoodooI2C/VoodooI2C/issues/319 AND/OR https://github.com/VoodooI2C/VoodooI2C/issues/435

**System Environment**
Please answer:
1. Catalina
2. Latest AND self compiled. VoodooI2C + VoodooI2CHID
3. Intel i5-10210 - 16GB RAM - 512GB SSD

I'm researching this issue for some days now and after reading a lot of the threads and forum and voodooi2c gitter chat logs i don't know what else do.
My laptop has a touchpad and a touchscreen. On I2C0 in ACPI table i see also a device called (NFC)
The problem is i always get Timeout waiting for device to complete host initiated reset on both TPDE AND TPL1 device if i use the latest voodooi2c from repository. I tried rebooting 20 times with always the same result.
After reading some opened and closed issues i self compiled VoodooI2C increasing timeout as saw here https://github.com/VoodooI2C/VoodooI2C/issues/319 with even higher values.
After that i have a 25% chance of timeout as before but when this is not the case i got a fully working touchscreen (gesture included) and a really laggy but working touchpad at the point to be useless (the arrow moves really slow BUT left click and right click are recognized immediately).

I followed istruction on issues 319 and modded my files accordingly but until i increased timeout i wasn't able to make things improve.

Attached you will find ioreg & kernel log for both the situations (I also included SSDT-I2C.aml as instructed in the Troubleshoot documentation so you should see it in ioREG)
[Timeout.zip](https://github.com/VoodooI2C/VoodooI2C/files/6447569/Timeout.zip)
[NO_Timeout.zip](https://github.com/VoodooI2C/VoodooI2C/files/6447570/NO_Timeout.zip)
[DSDT.aml.zip](https://github.com/VoodooI2C/VoodooI2C/files/6453474/DSDT.aml.zip)

UPDATE : 
I kept experimenting and i can add some more information about my issue.
I discovered that an important role to make that touchpad functional (meaning the arrow moves but super laggy) is the presence of SSCN and FMCN which are not present in my original DSDT.
I'm currently using this values : SSCN 432,507,30 and for FMCN 72, 160, 30..
I've found this values in different places (gitter page and some repositories for laptop similar to mine) so i'm using them.
Without SSCN and FMCN i got : 
VoodooI2CControllerDriver::pci8086,2e8 I2C Transaction error details
VoodooI2CControllerDriver::pci8086,2e8 lost arbitration
VoodooI2CControllerDriver::pci8086,2e8 I2C Transaction error: 0x0a001000 - aborting

So maybe this values make the touchpad "working" but are not optimal for my touchpad ? And if this is the case how can i obtain the correct values ? For example taking them from windows or linux where the touchpad works even with gestures ...

UPDATE 2 : 
After various tries i was able to enforce polling mode and the trackpad is working perfectly! No more laggy arrow and gesture are working too.
So my guess here is that GPIO is broken for some reasons which i can't understand. 
Now i would like to know if some of the devs are interesting in researching on this issue or i should close this report.

UPDATE 3: 
I've solved the timeout issue and changed the title because now i've only the laggy input problem.
If i use VoodooGPIO from 2.4.1 i don't have lag but i've an high cpu usage due to kernel_task
If i use VoodooGPIO from 2.4.2 i have lag and high cpu usage. The touchpad is laggy but usable
Aney version after 2.4.2 i have lag but no high cpu usage. The touchpad is not usable because according to Fingermgmt i have always a finger on the touchpad even when my finger is lifted.

@Goshin As you commited all the VoodooGPIO modifications .. could you please help me solve this issue ?
Thanks
Mattia

**Comment by Goshin** [comment]
Can you get your touchpad working well in GPIO mode with your touchscreen disabled or in polling mode? If so it could be a problem in VoodooGPIO. You can try out the commit I mentioned in https://github.com/VoodooI2C/VoodooI2C/issues/435#issuecomment-785810972 with the latest VoodooI2C&GPIO.

**Comment by tmbt78** [comment]
@Goshin I've tried that already. If i disable the touchscreen doesn't change anything. If i try to enforce polling mode to the touchscreen it seems succesfull according to the logs but the touchscreen doesn't work at all. 
So the only solution i've right now is to enforce polling mode on the touchpad and then i can use interrupt mode on the touchscreen o disable it doesn't matter.
My problem is that i use the laptop mostly on battery and i when in polling mode the laptop consume 1.4W while on interrupt i'm at around 0.8W .. so it's a huge difference for me.
Is there something else i can try ?

**Comment by tmbt78** [comment]
I've finally solved this issue !
The problem for the laggy pointer was here: Name (SBFG, ResourceTemplate ()
            {
                GpioInt (**Edge**, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,
                    )
                    {   // Pin list
                        0x0000
                    }
            })
I hotpatched the SBFG method changing **Edge to Level** and now the cursor isn't laggy anymore !
@Goshin @kprinssu Not sure if there is something to check on VoodooI2C side or if it is simply a problem with my DSDT but thanks again for your time

Mattia

**Comment by Goshin** [comment]
Congrats. It should be level interrupt according to Microsoft's I2C HID spec.

**Comment by kprinssu** [comment]
Thanks for update @tmbt78. Glad you got it working.
