### ISSUE TITLE
Intel comet lake i2c elan062F TPD2 device not working.

### ISSUE THREAD

**Issue by Aamirswati2** [VoodooI2C/VoodooI2C#457]
hello,
I manage to boot into big sur but the Trackpad is not working. i try to follow the guide for i2c but my dsdt is totally different from the guide.
I try polling mode but it is detecting the  device TPD4 and mine is TPD2 also the gpio pinning is not working.
anyone who can fix it.
i have attached my dsdt file
thanks
[DSDT.zip](https://github.com/VoodooI2C/VoodooI2C/files/6454661/DSDT.zip)

**Comment by kprinssu** [comment]
VoodooI2C has supported Comet Lake since June 2020 (see https://github.com/VoodooI2C/VoodooI2C/pull/335). 

Please actually read the Github issue template as this most likely a configuration error. Please use Gitter.
