### ISSUE TITLE
ELAN0626 issues

### ISSUE THREAD

**Issue by wtfcxt** [VoodooI2C/VoodooI2C#461]
**Describe the bug**
ELAN0626 I2C trackpad is not working

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. macOS Big Sur
2. 2.6.5
3. IdeaPad L340 15IRH Gaming w/ ELAN trackpad

**Troubleshooting Archive**
-will add soon when I'm at home-

**Additional context**
none

**Comment by kprinssu** [comment]
Please properly fill out the Github issue form and with a descriptive explanation of your issue. Simply saying it does not work is not at all helpful.

Once you have done so, please feel free to re-open this issue.
