### ISSUE TITLE
ELAN0626 no input at all

### ISSUE THREAD

**Issue by wtfcxt** [VoodooI2C/VoodooI2C#462]
**Describe the bug**
ELAN0626-based touchpads won't work. Neither interuppts, nor polling mode is working. 

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. macOS Big Sur 11.4
2. VoodooI2C 2.6.5
3. see code block
```
Model: Lenovo IdeaPad L340-17IRH Gaming
Touchpad: ELAN0626 I2C
SSD: WDC PC SN520 SDAPMUW-512
CPU: i5-9300H (Coffee Lake-H)
```

**Troubleshooting Archive**
[Troubleshooting Archive.zip](https://github.com/VoodooI2C/VoodooI2C/files/6771870/Troubleshooting.Archive.zip)

**Comment by kprinssu** [comment]
Your IO Registry file is corrupted. You are most likely using a version that does not work. 

Additionally, this is a configuration issue, please use Gitter for support.
