### ISSUE TITLE
TPD0 Trackpad not working.

### ISSUE THREAD

**Issue by michaelanhvu83** [VoodooI2C/VoodooI2C#465]
Hi. My Trackpad is TPD0, in my DSDT it inside I2C2. But in Ioreg, it showing me I2C0. How to fix this and make trackpad is working?
![Screen Shot 2021-07-20 at 18 15 37](https://user-images.githubusercontent.com/16274116/126318372-21825133-22f5-4125-9886-e494ab7dae25.png)
![Screen Shot 2021-07-20 at 18 44 11](https://user-images.githubusercontent.com/16274116/126318380-a9891290-f5ac-4707-a9d5-d6af7f03ed40.png)
![Screen Shot 2021-07-20 at 18 44 23](https://user-images.githubusercontent.com/16274116/126318382-723129ee-6b5f-4f4d-aa06-6889b3d6aeee.png)

**Comment by kprinssu** [comment]
Please use Gitter for support as this a configuration issue. Next time, _**please read**_ support documentation AND _**fill in**_ the GitHub issue template.
