### ISSUE TITLE
Acer TravelMate P215-52

### ISSUE THREAD

**Issue by fabien4455** [VoodooI2C/VoodooI2C#466]
**Describe the bug**
Trackpad not working

**Did you read the common errors documentation?**
no 

**Did you read the troubleshooting documentation?**
no 

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. What is your operating system? MacOS Catalina 10.15.7
2. What version of the drivers (including drivers) are you using? Voodoo I2C 2.6.5
3. What is your hardware configuration? Acer TravalMate P215-52, i3-10110U

**Troubleshooting Archive**

I tried couple versions of Voodoo I2C, my trackpad is not responsive, I can't use it. USB mouse is working, internal keyboard works

**Additional context**
I want to fix the issue, if I do anything wrong, please tell me how I can send you more information about my problem to help you.

**Comment by kprinssu** [comment]
Please use Gitter for support.
