### ISSUE TITLE
Multitouch gesture not working on the touchscreen with the stylus pen. (ZenBook Pro Duo 15 UX582)

### ISSUE THREAD

**Issue by shiecldk** [VoodooI2C/VoodooI2C#467]
**Describe the bug**
Multitouch gesture not working on the touchscreen with the stylus pen on the secondary screen in ASUS ZenBook Pro Duo 15 (has the main 4k and secondary touchscreens. Only the cursor and click functions work. (multi touch, scroll, and hold to drag/right click functions are not available.) The secondary touchscreen comes with stylus pen and support multi touch in Windows 10 and Ubuntu). Had tried disconnected the main touchscreen (unplug the eDP connector from MB), and had only the secondary screen in macOS 10.15.7. However, the issue remains the same. (only the cursor and click functions work.)

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
1. What is your operating system?  macOS 10.15.7
2. What version of the drivers (including drivers) are you using? Lasest (2.6.5)
3. What is your hardware configuration? (ASUS ZenBook Pro Duo 15, ELAN device id: ELAN9008 and ELAN9009, are in I2C2.TPL0 (Secondary Touchscreen with Stylus) and I2C3.TPL1 (Main Touchscreen), respectively; I2C0 is ELAN trackpad.)

Debug files:
https://drive.google.com/file/d/1fB-K3Dw2CISDaLb6qZmpKOe4xM14fe5_/view?usp=sharing

Similar issues in
https://github.com/VoodooI2C/VoodooI2C/issues/317
https://github.com/VoodooI2C/VoodooI2C/issues/188
https://github.com/VoodooI2C/VoodooI2C/issues/275

Is there any change I can make and test in:
VoodooI2CHIDDevice.cpp
VoodooI2CHIDTransducerWrapper.cpp
VoodooI2CMultitouchHIDEventDriver.cpp
VoodooI2CStylusHIDEventDriver.cpp
VoodooI2CTouchscreenHIDEventDriver.cpp 
to make the multitouch work in the stylus touchscreen?

Also, any way for me to join as contributor in this project?

<img width="522" alt="Screen Shot 2021-08-06 at 12 20 34 AM" src="https://user-images.githubusercontent.com/42949962/128457958-ade79ee7-f51f-4cb1-9d22-51b9b1aff204.png">

**Comment by kprinssu** [comment]
Please use the VoodooI2C Dev channel for support. GitHub is not the right place for support with the project.

In general, VoodooI2C does support stylus but implementation of has been spotty as macOS *does not* support natively.

**Comment by shiecldk** [comment]
@kprinssu I have asked help on the Dev channel on Gitter already  many time but on one was really answering and help there, so could you keep this topic opening? I don't see the reason why you close this topic; this problem has presented in other laptops too many time and I want to resolve this problem as it was never really been resolved before.

**Comment by kprinssu** [comment]
The dev channel is https://gitter.im/alexandred/VoodooI2CDev

Please ask on there for further help with the code.
