### ISSUE TITLE
Gestures voodooi2c elan 1010

### ISSUE THREAD

**Issue by radiolip** [VoodooI2C/VoodooI2C#470]
Voodooi2c.kext & VoodooI2CHID.kext trackpad work like a mouse. No gestures & touchpad. Big Sur.

ELAN 1010 I2C.

[DSDT.zip](https://github.com/VoodooI2C/VoodooI2C/files/7030907/DSDT.zip)

<img width="805" alt="7" src="https://user-images.githubusercontent.com/9461399/130426938-f8b605f4-aade-4aa5-a863-5156ff74d6b2.png">

<img width="944" alt="9" src="https://user-images.githubusercontent.com/9461399/130428938-4510a9fb-c8e3-4742-8307-a0f36cef05b7.png">

**Comment by kprinssu** [comment]
These screenshots are not helpful. 

Please read the GitHub issue template and fill it in. This is clearly a configuration issue, please use Gitter for support.
