### ISSUE TITLE
Latest Voodooi2c and Dell XPS 2-in-1 7390: Can't get Touchscreen and Trackpad wont work together.

### ISSUE THREAD

**Issue by achernolevski** [VoodooI2C/VoodooI2C#471]
Guys, never posted on git bug report before so apologize if doing it wrong. At this point, have nearly flawless Big Sur setup on the 7390 with the exception of touchscreen. 

I'm using the latest's voodooi2c combined with the "SSDT-OCI2C1-TP01-xps9300". This gets me the touchpad to work perfectly but not the touch screen. I saw that this bug was by @M69W and he posed the solution of SSDT-TPDX that uses pin 1b. I tried that and still no go. 

IM attaching the SSDT I'm using and my original dsdt if needed. Would really appreciate
 the help!

[dsdt.zip](https://github.com/VoodooI2C/VoodooI2C/files/7102330/dsdt.zip)
[SSDT-OCI2C1-TP01-xps9300.zip](https://github.com/VoodooI2C/VoodooI2C/files/7102336/SSDT-OCI2C1-TP01-xps9300.zip)

**Comment by kprinssu** [comment]
Please re-open after filling in the Github issue template. The AML files are useless without the extra information (IOReg, EFI folder, etc.).
