### ISSUE TITLE
Screenshots are missing on voodooi2c.github.io

### ISSUE THREAD

**Issue by madfanat** [VoodooI2C/VoodooI2C#475]
I can't pin GPIO, because there are no screenshots on voodooi2c.github.io.

**Comment by ben9923** [comment]
Thanks. Will be fixed once the linked PR is merged :)

**Comment by madfanat** [comment]
> Thanks. Will be fixed once the linked PR is merged :)
Thanks.

**Comment by ben9923** [comment]
Verified it works now :)
