### ISSUE TITLE
Tiger Lake on HP Probook 450 G8 trackpad not work

### ISSUE THREAD

**Issue by gianlucainnocenti** [VoodooI2C/VoodooI2C#478]
**Describe the bug**
I tray to use voodool2c on my laptop with support of Avery Black @1Revenger1 but my trackpad want work

I use Big Sur 11.5 latest version of voodool2c 
I attach dmesg and screenshot....
![Screenshot 2021-09-15 at 09 39 34](https://user-images.githubusercontent.com/56543981/133397625-dfedfe8e-b735-468f-8e9a-4db749d9f8e4.png)
[dmesg_now.zip](https://github.com/VoodooI2C/VoodooI2C/files/7168171/dmesg_now.zip)

**Comment by gianlucainnocenti** [comment]
Thank you in Advance..

**Comment by kprinssu** [comment]
Please use Gitter for support.

**Comment by m0d16l14n1** [comment]
>  Please actually read the Github issue template and fill it in. @ben9923 mentions that Tiger Lake is not supported by VoodooI2C.
> 
>  
> 
>  Simply uploading logs and a screenshot is not enough to troubleshoot.

I am not sure that you really *need* to support Tiger Lake until it will get graphics support on macOS (acceleration). It's not supported at all by now

**Comment by gianlucainnocenti** [comment]
I am been using my laptop with 11th Gen intel

**Comment by ben9923** [comment]
@m0d16l14n1 I believe it will never be supported :/
Maybe for those with eGPU/built-in AMD graphics?

@gianlucainnocenti Your IOReg shows no graphics hardware acceleration for iGPU.

**Comment by gianlucainnocenti** [comment]
Yes I know, infact I have only 7mb but this issue will solve:)

**Comment by m0d16l14n1** [comment]
> @m0d16l14n1 I believe such graphics will never be supported :/
> 
> Maybe for those with eGPU/built-in AMD graphics?
> 
> 
> 
> @gianlucainnocenti Your IOReg shows no graphics hardware acceleration for iGPU.

You are right, maybe with AMD dGPU wired directly to internal screen / eGPU it might be possible. Might be possible that Tiger Lake needs same D3 patch as Comet/Ice have and to include new pci ids?

**Comment by gianlucainnocenti** [comment]
@m0d16l14n1 Yes, could be, I am verifying some info about...I hope to find a solution..
Thank for your message:)

**Comment by gianlucainnocenti** [comment]
@ben9923 Do you have some instruction about "D3 Patch" and "IDs should be added to match the ICL/CML+ class "

**Comment by ben9923** [comment]
> @ben9923 Do you have some instruction about "D3 Patch" and "IDs should be added to match the ICL/CML+ class "
> 
> 

You already did it by adding the ID to the proper location in the Info.plist.

**Comment by gianlucainnocenti** [comment]
@Graphic id you mean?!Or l2c id?

**Comment by ben9923** [comment]
> @Graphic id you mean?!Or l2c id?

I2C...

**Comment by gianlucainnocenti** [comment]
@ben9923 ok ...scuseme

**Comment by ben9923** [comment]
> @ben9923 ok ...scuseme...File I uploaded are correctly? Let me know

An example would be the archive you've uploaded to Gitter. It has ACPI, IOReg, logs, etc.

**Comment by ben9923** [comment]
Confirmed to work by adding PCI IDs to the ICL+ class in Info.plist
Requires `force-polling` as VoodooGPIO doesn't support Tiger Lake yet.

Once both changes will be merged to master (& tested) we can close this issue.
CC @kprinssu

**Comment by kprinssu** [comment]
This should be added within 2.7, please test using the latest release. If not, please re-open this issue.
