### ISSUE TITLE
ELAN TouchScreen not working

### ISSUE THREAD

**Issue by alkindivv** [VoodooI2C/VoodooI2C#481]
**Describe the bug**
ELAN I2C TouchScreen Does not work in macOS but it Does work in BIOS/OpenCore GUI Menu.

**Did you read the common errors documentation?**
YES

**Did you read the troubleshooting documentation?**
YES

**Have you searched the issue on Github, Gitter, or Google?**
YES

**System Environment**
Please answer:
1. macOS Big Sur 11.2
2. Release 2.6.5
3. Synaptics TrackPad and ELAN

![Screen Shot 2021-10-01 at 09 00 40](https://user-images.githubusercontent.com/66145311/135554428-b6e459bb-7628-468c-8201-f011445e517f.png)

**Comment by kprinssu** [comment]
Please re-open after attaching the proper troubleshooting files.
