### ISSUE TITLE
Dell latitude 7490 - trackpad does not work - opencore

### ISSUE THREAD

**Issue by franklin-gedler** [VoodooI2C/VoodooI2C#484]
model: DELL081C
[https://www.driveridentifier.com/scan/synapticsr-i2c-miniport/driver-detail/6EFCCF801FE942A4B52BCA90A3F040FE/3324309/5ad23bc17b9c4d8ae2aec32ec3b66912/1253779980/PNP0C50](url)

hello I hope you are fine, I am not able to enable the trackpad, I tried loading the following:

VoodooI2C.kext and VoodooI2CSynaptics.kext : unsuccessfully
VoodooI2C.kext and VoodooI2CHID.kext : unsuccessfully

any clues that i'm missing? thanks

**Comment by kprinssu** [comment]
Please use Gitter for support with setting up your configuration.
