### ISSUE TITLE
The trackpad is recognized as a trackpad and mouse

### ISSUE THREAD

**Issue by MrSu0215** [VoodooI2C/VoodooI2C#490]
The trackpad is recognized as a trackpad and a mouse. I only need the system to recognize the trackpad as a trackpad hardware, not as a mouse. How should I adjust it?
![image](https://user-images.githubusercontent.com/55876369/148689222-a281afca-bb8d-475f-aad3-a5f1a17e0ad2.png)

Only the trackpad is required
![image](https://user-images.githubusercontent.com/55876369/148689227-d5e32722-b9a4-40b5-9c8a-d615455af028.png)

How to solve this problem please?

**Comment by kprinssu** [comment]
Please use Gitter for support with configuration.

Please also thoroughly read the troubleshooting documentation and fill in the GitHub issue template.
