### ISSUE TITLE
Thinkpad Yoga 370 has some major problems

### ISSUE THREAD

**Issue by duszmox** [VoodooI2C/VoodooI2C#492]
I use VoodooPS2 controller and VoodooHID on my laptop but there are few problem that I can't solve.
For starters when I press down more then, two keys on my keyboard the trackpad freezes for a second and I can't use it, and the same thing happens when I use my trackpad buttons. And the second one is the trackpad isn't waking up from sleep, I found a semi-fix in [this repo](https://github.com/geoleonsh/clover-EFI-yoga-370), but after the second time waking up from sleep, the trackpad can't wake up. I linked my EFI folder and my DSDT.aml exported from windows. I would really appreciate the help
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7940617/EFI.zip)
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/7940669/DSDT.aml.zip)
[opencore-2022-01-26-094851.txt](https://github.com/acidanthera/bugtracker/files/7940697/opencore-2022-01-26-094851.txt)

**Comment by kprinssu** [comment]
This is not the place for support for with your configuration. Please use Gitter for support.
