### ISSUE TITLE
Workarounds needed to prevent incorrect matching of satellite drivers to touch devices

### ISSUE THREAD

**Issue by gvkt** [VoodooI2C/VoodooI2C#494]
I am opening this issue to discuss possible solutions to this problem. While this has come up specifically with Screenpads in ASUS laptops, the problem is more generic and applies to things like the second screen in ASUS Duos. So, I will capture the general problem so as not to precipitate a hack specifically for Screenpads.

The current set of satellites for trackpads and touch screens depend on the driver matching mechanism of IOKit using the information in the Info.plist packaged into the kext.

This has traditionally worked well when there were just simple trackpads or just touch screens or a combination of the two.

Things like Screenpads or secondary screens that can work in multiple modes - as a touch screen or a trackpad - break this system. A trackpad matched to a touch screen driver will not work if its primary/default mode is as a trackpad even though its static properties such as the report descriptors make it available as a touch screen. 

This is what happens with Screenpads in ASUS laptops by default and therefore requires users to hack the Info.plist to make it work. Besides the fact that this is difficult for non-developer type users, it is not always obvious what the hack should be.

For example, if the laptop has a Screenpad but no touch screen then the probe score for the trackpad driver can be increased to make it higher priority than touch screen driver and it works. But if the laptop also has a touch screen then that change can result in the touch screen not attaching to the touch screen crippling that functionality.

One could force these assignments using matching of device product IDs but that would be specific to each type of vendor and model number used by the laptop manufacturer and still would need Info.plist hacking at every update. Or create specialized kexts for specific hardwired product ids amd updated whenever a new product id was found deployed.

Ideally, one should be able to “override” the default matching when needed with a boot argument or a quirk specification leaving the kext untouched so it can be updated at any time.

**Comment by kprinssu** [comment]
@gvkt Devices with screenpads are bit exotic and are currently on some Zenbooks. The combination of hardware is quite rare and I am bit reluctant to support within VoodooI2CHID as it would require an extensive rewrite. Considering that, how exotic the hardware is and  the lack of hardware to test with, I am bit reluctant to support this nor add support for it.

Anyone who wants this to be supported should modify the Info.plist and change IO Probe score.
