### ISSUE TITLE
In Recovery clicking with separate physical button requires a finger to be on the touchpad

### ISSUE THREAD

**Issue by usr-sse2** [VoodooI2C/VoodooI2C#499]
If there are no fingers on the touchpad, clicks are ignored.

**Comment by kprinssu** [comment]
@usr-sse2 Does https://github.com/VoodooI2C/VoodooI2C/commit/9ab98319b6411c4a4822cc12f840df85cc684bfc address this? It contains your changes from PR#503.

**Comment by kprinssu** [comment]
Closing as this should be fixed by [`9ab98319b6411c4a4822cc12f840df85cc684bfc`](https://github.com/VoodooI2C/VoodooI2C/commit/9ab98319b6411c4a4822cc12f840df85cc684bfc). Please comment if it is not.
