### ISSUE TITLE
Atml3000 working

### ISSUE THREAD

**Issue by Fvm94** [VoodooI2C/VoodooI2C#502]
Only these kexts activate my touchpad. but if I update to the last version stops working, can u help me to add this to the main version?

"Here is a build of VoodooI2C/VoodooI2CHID#59 PR without the other two PRs added to them."
[Archive 5.zip](https://github.com/VoodooI2C/VoodooI2C/files/8027221/Archive.5.zip)

_Originally posted by @1Revenger1 in https://github.com/VoodooI2C/VoodooI2C/issues/491#issuecomment-1033031136_

**Comment by kprinssu** [comment]
Dev builds on Github PRs and issues are not supported. Please create a detailed Github issue with the template filled out.
