### ISSUE TITLE
No Trackpad functionality what so ever: HP Pavillion x360 ELAN0722

### ISSUE THREAD

**Issue by Babyyoda777** [VoodooI2C/VoodooI2C#506]
I have tried all the VoodooI2C, VoodooPS2, VooodooSMbus plugins but none seem to work.
CPU: i3 1005G1
Kexts used are all the latest, I am using Voodooi2c with the HID plugin
I have had no luck whatsoever and am now stuck on what to try next.
![Screen Shot 2022-06-02 at 12 54 26](https://user-images.githubusercontent.com/80623330/171623770-42b0ff5b-65ec-4a3a-9c04-5b1cf0e59324.png)
It seems I have correctly pinned my GPI0, but here is a screen shot incase.
I followed the Dortiana guide and checked all he trouble shooting issues.

**Comment by Babyyoda777** [comment]
[Azlan’s MacBook Air.zip](https://github.com/VoodooI2C/VoodooI2C/files/8823508/Azlan.s.MacBook.Air.zip)
Here is an IOReg of the mackintosh

**Comment by kprinssu** [comment]
Please use Gitter for support with configuration.
