### ISSUE TITLE
kernel panic with VoodooI2CHID in macOS Ventura

### ISSUE THREAD

**Issue by gujiangjiang** [VoodooI2C/VoodooI2C#508]
**Describe the bug**
In macOS Ventura my laptop cant wake up from sleep.
when wake up than it reboot and show kernel panic in next boot (5 countrys).
I'm using VoodooI2C and VoodooI2CHID to make my I2C touchpad and USB touchscreen works.
It works well in macOS 12.x 11.x but have wake up problem in 13.x
I have tried delete VoodooI2CHID and then it works well and can wake up from sleep with no problem.

Now i have test these combination:
Delete VoodooI2CHID
Preserve VoodooI2C
Add VoodooRMI.kext/Contents/PlugIns/RMII2C.kext

then my I2C touchpad works well and have no problem in sleep and wake up but my USB touchscreen don't works anymore.

So I hope to fix VoodooI2CHID in macOS Ventura.

Thanks.

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system?      **macOS Ventura**
2. What version of the drivers (including drivers) are you using?    **Latest version**
3. What is your hardware configuration?    **XPS15-9550 with i7-6700HQ**

When kernel panic reboot into the macOS it always show HID error.
<img width="1000" alt="223018efn01on8cao1a81i" src="https://user-images.githubusercontent.com/13273955/175309428-d4fa51a9-fe45-4aa3-9afe-3ad2c92c9d46.png">

**Comment by kprinssu** [comment]
This is the same panic as issue 507. Next please, please avoid creating duplicate issues.
