### ISSUE TITLE
trackpad not found

### ISSUE THREAD

**Issue by Habooooob** [VoodooI2C/VoodooI2C#512]
hello everyone

i am new user to mac community

i just installed Olarila Catalina 10.5.7 over opencore

and every thing is ok except trackpad not found

iam now using usb mouse but i need to use trackpad of my laptop fujitsu lifebook e5510

cpu commt lake QuadCore Intel Core i5-10210U, 4100 MH

trackpad all functions not working  mouse and all clicks not working

its elan i2c as shown in screenshot attracted  and uploaded efi folder and in kext i use VoodooI2C 2.7 and not working also

**Comment by kprinssu** [comment]
Please use Gitter for configuration support. Please fill out issue template next time.
