### ISSUE TITLE
HP Tilt pen recognised as keyboard and has no pen input.

### ISSUE THREAD

**Issue by Babyyoda777** [VoodooI2C/VoodooI2C#513]
So I am trying to get my HP Tilt Pen to recognise input on MacOS. After lots of searching, I found that in ControllerMate, that MacOS KNOWS where the input is precisely, and it can tell that there is input being recieved, but unfotunately, I believe the issue is that MacOS is recognising it as a Keyboard than as a pen/mouse. The pen has two buttons, and the larger eraser button works nicely, and I have been able to map it using Controllermate to open safari upon click. Infact, controllermate even reports the pressure sensitivity as working, which was a surprise. 

The X-axis and Y-axis are both using precision touch, with 10000 by 180000 precision input points as in windows, and pressure sensitivty also going up to 10000 points.

I think really the main issue is that macos detects it as a keyboard, and a simple solution would be to simply interpret it as a mouse/touchpad with precision pointing as with a touchscreen, and maybe even add palm rejection if possible. The pen does connet by bluetooth normally. I am using the latest version of VoodooI2C and VoodooI2CHID.

I have already asked on gitter with no one having any idea of how to help, and well as having researched extensively elsewhere.

**Comment by kprinssu** [comment]
Please re-open this issue after filling out the Github issue template alongside troubleshooting files.
