### ISSUE TITLE
I have problem please tell me how i can slove it

### ISSUE THREAD

**Issue by MohamedSaberM** [VoodooI2C/VoodooI2C#516]
hello, how i can solve it ?
(VoodooI2CELAN) <compose failure [UUID]>
 localhost kernel[0]: (VoodooI2CELAN) VoodooI2CELANTouchpadDriver::elan Touchpad probe
 localhost kernel[0]: (VoodooI2CELAN) VoodooI2CELANTouchpadDriver::elan ELAN device found (ELAN061F)
 localhost kernel[0]: (VoodooI2CELAN) VoodooI2CELANTouchpadDriver::elan Could not get interrupt event source, trying to fallback on polling
 localhost kernel[0]: (VoodooI2CELAN) VoodooI2CELANTouchpadDriver::ELAN061F Failed to write RESET cmd
localhost kernel[0]: (VoodooI2CELAN) VoodooI2CELANTouchpadDriver::elan Failed to init device

os:ventura beta 7

**Comment by kprinssu** [comment]
Next time, please read the documentation and fill in the Github issue template. This is an issue with your configuration, please use Gitter.
