### ISSUE TITLE
i2c-hid Touchpad gestures not working, dell Inspiron 3593, macOS Monterey 12.6.1

### ISSUE THREAD

**Issue by HDV998** [VoodooI2C/VoodooI2C#518]
hi, I have a dell Inspiron 3593 on Monterey 12.6.1 via opencore 0.8.5, my touchpad gestures is not working no matter what I do, my voodoo gpio is attached to GPI0, 
![image](https://user-images.githubusercontent.com/91041845/201530456-97c37e7c-83cf-44c9-838c-96a2ae7df46e.png). 
I tried adding the kexts, applied the XOSI patch but still doesn't work, then I made the gpio and osys ssdt, but gestures still don't work, the option of gestures don't even show up in settings. pls ask for any other info required

also in windows device manager it shows my id is TPD0
[EFI.zip](https://github.com/VoodooI2C/VoodooI2C/files/9997634/EFI.zip)

**Comment by kprinssu** [comment]
Please use Gitter for support with your configuration.
