### ISSUE TITLE
MSFT0001 touchpad not working

### ISSUE THREAD

**Issue by izwb003** [VoodooI2C/VoodooI2C#522]
**Describe the bug**
A Lenovo ThinkBook 15p laptop with a MSFT0001 touchpad, but the touchpad does not work under macOS.

**Did you read the common errors documentation?**
Yes. I've searched the log but no relevant text found.

**Did you read the troubleshooting documentation?**
Yes. I'm looking for help here.

**Have you searched the issue on Github, Gitter, or Google?**
Yes, I've tried many ideas, but with no luck...
I've read #450 #388 #218 but:
Cannot find variable GPHD and TPDM in my system DSDT. (Only some "if" sentences)
Tried -vi2c-force-polling but still not working.
Tried to pin GPIO by the tutorial but still not working.

**System Environment**
Please answer:
OS: macOS Monterey 12.5(21G72)
Driver: VoodooI2C 2.7
Hardware: Lenovo ThinkBook 15p/i7-10870H/16GB DDR4/1TB SanDisk SSD (installed by myself)/MSFT0001 touchpad under PCI0.I2C1.TPD0

**Troubleshooting Archive**
[Archive.zip](https://github.com/VoodooI2C/VoodooI2C/files/10328337/Archive.zip)

**Additional context**
Also installed VoodooPS2Controller 2.3.0 with VoodooPS2Keyboard 2.3.0.
I use VoodooInput from VoodooI2C 2.7.
IORegistryExplorer detected the touchpad correctly.

**Comment by kprinssu** [comment]
Please use Gitter for support with setting up your configuration.
