### ISSUE TITLE
Numpad for ASUS Trackpad

### ISSUE THREAD

**Issue by shiecldk** [VoodooI2C/VoodooI2C#524]
For Linux, there is a GitHub repo that enables the Numpad function for ASUS Laptop's Trackpads:
https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver

I am hoping someone can port the python program and modify VoodooI2C to make the numpads on the trackpads work for ASUS laptops.

**Comment by kprinssu** [comment]
Keyboards are not currently supported within VoodooI2C; this expands to numpad support as well. I do not any plans to support keyboards. As always PRs are welcome.

**Comment by Qonfused** [comment]
For clarity, this is a numpad driver for ASUS *trackpads*, not keyboards.
