### ISSUE TITLE
VoodooI2C v2.8 not support macbook m1

### ISSUE THREAD

**Issue by Leondrx0623** [VoodooI2C/VoodooI2C#528]
Describe the bug
when use the voodool2C and voodool2CHID driver, my intel-macbook runs perfectly. But my m1 mac loaded the kext failed.

Did you read the common errors documentation?
yes

Did you read the troubleshooting documentation?
yes

Have you searched the issue on Github, Gitter, or Google?
yes

System Environment
Please answer:

What is your operating system?
macos 13 Ventura 13.2.1

What version of the drivers (including drivers) are you using?

v2.8

What is your hardware configuration?
Macbook m1
16g 512g

**Comment by kprinssu** [comment]
VoodooI2C does not support Apple hardware.
