### ISSUE TITLE
Feature Request: AMD I2C Support

### ISSUE THREAD

**Issue by DavidACrompton** [VoodooI2C/VoodooI2C#529]
**Describe the bug**
Now that the WhateverRed Kext can add graphics acceleration for AMD Ryzen graphics, it might be a good time to revisit the stance in issue #418 that support for AMD I2C is not planned. 

My Ryzen hackintosh laptop is fully functional (Graphics acceleration, Wi-Fi, Bluetooth, keyboard) with the exception of the elan touchpad. Meaning I have to always have a USB mouse connected to the laptop. 

With usable laptop builds for AMD now being possible and usable, could support be added for AMD I2C?

**Did you read the common errors documentation?**
N/A

**Did you read the troubleshooting documentation?**
N/A

**Have you searched the issue on Github, Gitter, or Google?**
Yes #418 

**System Environment**
Please answer:
1. What is your operating system? MacOS Big Sur
2. What version of the drivers (including drivers) are you using? N/A
3. What is your hardware configuration?
AMD Ryzen 5 CPU
Lenovo V15-ADA laptop with WhateverRed for graphics acceleration 

**Additional context**
This is a feature request for the addition of AMD I2C support

**Comment by kprinssu** [comment]
This was previously asked before and we have no plans to do so.

I personally don't have the hardware on hand. PRs are always welcome.
