### ISSUE TITLE
Not working Skylake Ventura

### ISSUE THREAD

**Issue by nasiftanjim** [VoodooI2C/VoodooI2C#531]
VoodooI2C doesnt work, I have 2 skylake controllers: 9D60 & 9D93
I'm using macOS Ventura 13.3.1
9D60 controls my touchscreen
9D63 controls my touchpad (alps) & keyboard
None of them work, I've tried with XOSi patch, GPIO patch, nothing works.
Any suggestions to get them working?
Thanks.

**Comment by kprinssu** [comment]
Please use Gitter for support.
