### ISSUE TITLE
ELAN0000 unusable in polling, no input when pinned. 

### ISSUE THREAD

**Issue by isi95010** [VoodooI2C/VoodooI2C#536]
**Describe the bug**
In polling, cursor moves in short bursts every 3-26 seconds while continuously rubbing touchpad. A click can be achieved in those short intervals but it will be stuck and cannot "unclick". This unusable. 
(video available if needed)

When GPIO **pinned**, there is no input observed. 

Note: i2c child devices are defined in an OEM SSDT from the firmware, called SSDT-1.aml which I’ve included along with the DSDT. The touchpad is Device (D015) under I2C1. 
I’ve also included my pinning SSDT as I’m not static patching the DSDT. 

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes.

**System Environment**
Dell Chromebook 7410 with custom Coreboot firmware
Intel Core i7-10610U 
MacOS Ventura 13.4.1
VoodooI2C, VoodooI2CElan, 2.8

**Troubleshooting Archive**
[Elan0000 Dell 7410 Chromebook.zip](https://github.com/VoodooI2C/VoodooI2C/files/12114638/Elan0000.Dell.7410.Chromebook.zip)

**Additional context**

**Comment by kprinssu** [comment]
Please read the Github issue template. This *is not* for support with your config. Use Google or another resource for help.
