### ISSUE TITLE
I2C & CHID loaded but SYNA30D2 not working 

### ISSUE THREAD

**Issue by chteow** [VoodooI2C/VoodooI2C#537]
Hardware: HP Elite 845 G8 Ryzen 5 

Path: _SB.I2CA.TPAD & _SB.TPAD@0

During boot found busy timeout TPAD 

Attached IORegistryExplorer info
[ioreg](https://drive.google.com/file/d/1tud23lme6hwcIcoC1k9pP7UipQztKnMl/view?usp=share_link)

**Comment by kprinssu** [comment]
This is now closed due to the lack of details and not filling out the Github issue template.
