### ISSUE TITLE
VoodooI2C breaking sleep wake on MacOS Sonoma RC (as of 21st sep)

### ISSUE THREAD

**Issue by Mifaxav** [VoodooI2C/VoodooI2C#540]
**Describe the bug**

When VoodooI2C is enabled, touchscreen is perfectly fine but it breaks sleep and wake. disabling all the kexts causes the touchscreen to not function but with perfect sleep wake. 

**Did you read the common errors documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Common%20Errors/Common%20Errors

Not yet but I'm pretty sure touchscreen drivers breaking sleep is not common...

**Did you read the troubleshooting documentation?**
Please answer yes or no after reading https://voodooi2c.github.io/#Troubleshooting/Troubleshooting.

Nothing regarding macOS Sonoma

**Have you searched the issue on Github, Gitter, or Google?**
Please answer yes or no, this is to avoid creating duplicate Github issues.

Yes i have and no results. 

**System Environment**
Please answer:
1. What is your operating system? 

MacOS Sonoma 

2. What version of the drivers (including drivers) are you using?

Latest VoodooI2C drivers

3. What is your hardware configuration?

Im on a Lenovo T480 with a Core i5-8350U processor and a UHD620 GPU

**Troubleshooting Archive**
Please attach the troubleshooting archive (as per https://voodooi2c.github.io/#Troubleshooting/Troubleshooting) and any additional logs or videos demonstrating the problem. Please attach any extra files to Github and *not* anywhere else like Google Drive.

Laptop just reboots(when it is supposed to wake) when voodooI2C kexts are present but disabling all the I2C kexts, sleep wake is perfect.

**Additional context**

N/A

**Comment by kprinssu** [comment]
Please attach logs as per the troubleshooting section. Closing this issue until you read and properly fill out the Gthub issue template.

**Comment by Mifaxav** [comment]
![IMG_3202](https://github.com/VoodooI2C/VoodooI2C/assets/84403807/3dc53954-669a-42cf-a6c1-421b04919fe6)


that's an image reporting an improper sleep wake cycle. This issue only occurs when VooDooI2C is enabled in OpenCore. Disabling all those kexts, i can get perfect sleep wake with S4 hibernation working. I understand this is still in its release candidate form but these changes would most probably be continued into the final release. If needed, i can also test to make sure this issue is fixed.

**Comment by kprinssu** [comment]
One again, please read the https://voodooi2c.github.io/#Troubleshooting/Troubleshooting and attach all the logs and IO Registry files. This screenshot is not sufficient nor is it helpful.


This is mandatory and not optional.

**Comment by kprinssu** [comment]
This issue is now closed and locked due to the lack of a proper troubleshooting archive.
