### ISSUE TITLE
touchscreen dead at wake

### ISSUE THREAD

**Issue by Lorys89** [VoodooI2C/VoodooI2C#541]
notebook Dell Latitude 2 in 1 tablet
cpu i7 10810u
acpi origin/sysreport 
[Dump dell 7210 2in1.zip](https://github.com/VoodooI2C/VoodooI2C/files/12868454/Dump.dell.7210.2in1.zip)

log i2c after wake 
[dopo wake i2cLog.log](https://github.com/VoodooI2C/VoodooI2C/files/12868456/dopo.wake.i2cLog.log)

**Comment by Lorys89** [comment]
If you want I fill it out immediately, but it is a problem that wakes, loses the bus

**Comment by kprinssu** [comment]
As I mentioned on Gitter, I will not be able to help. The lack of information and just posting logs does not help. Please reach out for help on the VoodooI2CDev channel (not the general help channel) on Gitter.
