### ISSUE TITLE
VoodooI2C 2.8 causes macOS Sonoma to bootloop/crash

### ISSUE THREAD

**Issue by CrimKat** [VoodooI2C/VoodooI2C#542]
Dell XPS 15 9500
Intel UHD Graphics 630
Intel Core i7-10750H

Updated Voodol2C kext to 2.4.4 to 2.8, can confirm this caused macOS Sonoma to bootloop/crash. 
Using known working EFI and reverting to 2.4.4 stopped the bootlooping, so I can confirm that this was the cause.
Used OpenCore Auxillary tools to update kext.

**Comment by kprinssu** [comment]
This is now closed as you did not fill out the Github issue template. 

Please read and fill out the template.
