### ISSUE TITLE
Multiple issues with ELAN1200 on a ASUS X515J

### ISSUE THREAD

**Issue by itsmaclol** [VoodooI2C/VoodooI2C#544]
**Describe the bug**

**Drag click.**

Basically, when i hold with one finger, and drag with the other, the cursor jumps back, not allowing me to move the file check video of my POV [here](https://cdn.discordapp.com/attachments/302485086060937219/1130130210587680839/IMG_1830.mov), i tried a user's recommandation on hackintosh paradise's discord server which is by downgrading VoodooI2C + satellites to an older version, which fixed the drag issue, but i can no longer use the right click button (yes it is setup in trackpad settings in macOS)

**Random freezes**

The trackpad randomly freezes during use, this sometimes gets fixed when i close the lid of the laptop and i open it again, but 
does something which brings us to my next issue. Fixes tried: N/A

**Double click**

As i said before, this happens more frequently after closing the lid and opening it again from a freeze, but this can also happen randomly, what happens is when i click the trackpad (click, not touch) it double clicks, and doesen't do a single click, allthough when touycing the trackpad it does single click. Fixes tried: N/A

**Did you read the common errors documentation?**

Please answer yes or no after reading https://voodooi2c.github.io/#Common%20Errors/Common%20Errors

**Did you read the troubleshooting documentation?**

Yes

**Have you searched the issue on Github, Gitter, or Google?**

Yes

**System Environment**
**OS**: macOS Sonoma 14.1 RC 1 (Also tried with latest ventura, same issues)

**Drivers**: Tried multiple, more info at describing the bug

**System Specs**:

|          [CPU][Intel(R) Core(TM) i7-1065G7 (Ice Lake)]
| [Laptop Model][ASUS X515J aka X515JA]
|       [Memory][Samsung 8GB DDR4 3200MHz]
|       [Memory][Samsung 8GB DDR4 3200MHz]
|      [Storage][Micron 2450 500GB NVMe SSD]
|      [Storage][Kingston A400 240GB SATA SSD]
|         [iGPU][Intel(R) Iris(R) Plus Graphics]
|        [Wi-Fi][Dell Wireless 1560 (DW1560 aka BCM94352Z)]
|     [Keyboard][PS/2 Compatible Keyboard]
|     [Trackpad][ELAN 1200]
|     [Ethernet][N/A]
|     [Speakers][Internally USB Connected C-Media Speakers]
|       [SMBIOS][MacBookPro16,2]

**Comment by kprinssu** [comment]
This is a hardware issue, see https://github.com/VoodooI2C/VoodooI2C/issues/321.

Please use the search functionality before creating an issue.
