### ISSUE TITLE
Make it work with SYNA329F please

### ISSUE THREAD

**Issue by Lukitronix1467** [VoodooI2C/VoodooI2C#545]
**Describe the bug**
There's no support for SYNA329F Trackpad. No respond, not detected.

**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. What is your operating system?  MacOS Sonoma 14.3.1
2. What version of the drivers (including drivers) are you using? 
3. What is your hardware configuration? i7 10th gen (Ice lake) - Trackpad SYNA329F

**Comment by kprinssu** [comment]
As per the GitHub issue template, you need to read the documentation.

Your lack of details and troubleshooting archive does not help.
