### ISSUE TITLE
cant get it to work :(

### ISSUE THREAD

**Issue by Redmoneydash** [VoodooI2C/VoodooI2C#546]
`    Scope (_SB)
    {
        Scope (I2CD)
        {
            Device (TPDD)
            {
                Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
                {
                    If ((!I018 && I024))
                    {
                        If (I003)
                        {
                            Return ("ELAN0725")
                        }
                        Else
                        {
                            Return ("ELAN0727")
                        }
                    }
                    Else
                    {
                        Return ("ELAN0708")
                    }
                }

                Name (_CID, "PNP0C50" /* HID Protocol Device (I2C bus) */)  // _CID: Compatible ID
                Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
                {
                    Name (RBUF, ResourceTemplate ()
                    {
                        I2cSerialBusV2 (0x0015, ControllerInitiated, 0x00061A80,
                            AddressingMode7Bit, "\\_SB.I2CD",
                            0x00, ResourceConsumer, , Exclusive,
                            )
                        GpioInt (Level, ActiveLow, Exclusive, PullUp, 0x0000,
                            "\\_SB.GPIO", 0x00, ResourceConsumer, ,
                            )
                            {   // Pin list
                                0x0009
                            }
                    })
                    Return (RBUF) /* \_SB_.I2CD.TPDD._CRS.RBUF */
                }

                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    If ((I018 || I024))
                    {
                        Return (0x0F)
                    }

                    Return (Zero)
                }

                Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
                {
                    If ((Arg0 == ToUUID ("3cdff6f7-4267-4555-ad05-b30a3d8938de") /* HID I2C Device */))
                    {
                        Switch (ToInteger (Arg2))
                        {
                            Case (Zero)
                            {
                                Switch (ToInteger (Arg1))
                                {
                                    Case (One)
                                    {
                                        Return (Buffer (One)
                                        {
                                             0x03                                             // .
                                        })
                                    }
                                    Default
                                    {
                                        Return (Buffer (One)
                                        {
                                             0x00                                             // .
                                        })
                                    }

                                }
                            }
                            Case (One)
                            {
                                Return (One)
                            }
                            Default
                            {
                                Return (Zero)
                            }

                        }
                    }
                    Else
                    {
                        Return (Buffer (One)
                        {
                             0x00                                             // .
                        })
                    }
                }
            }
        }
    }

    Scope (_SB)
    {
        Scope (I2CD)
        {
            Device (TPNL)
            {
                Name (_HID, "ELAN2513")  // _HID: Hardware ID
                Name (_CID, "PNP0C50" /* HID Protocol Device (I2C bus) */)  // _CID: Compatible ID
                Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
                {
                    Name (RBUF, ResourceTemplate ()
                    {
                        I2cSerialBusV2 (0x0010, ControllerInitiated, 0x00061A80,
                            AddressingMode7Bit, "\\_SB.I2CD",
                            0x00, ResourceConsumer, , Exclusive,
                            )
                        GpioInt (Level, ActiveLow, Exclusive, PullUp, 0x0000,
                            "\\_SB.GPIO", 0x00, ResourceConsumer, ,
                            )
                            {   // Pin list
                                0x0059
                            }
                    })
                    Return (RBUF) /* \_SB_.I2CD.TPNL._CRS.RBUF */
                }

                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    If (I004)
                    {
                        Return (0x0F)
                    }

                    Return (Zero)
                }

                Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
                {
                    If ((Arg0 == ToUUID ("3cdff6f7-4267-4555-ad05-b30a3d8938de") /* HID I2C Device */))
                    {
                        Switch (ToInteger (Arg2))
                        {
                            Case (Zero)
                            {
                                Switch (ToInteger (Arg1))
                                {
                                    Case (One)
                                    {
                                        Return (Buffer (One)
                                        {
                                             0x03                                             // .
                                        })
                                    }
                                    Default
                                    {
                                        Return (Buffer (One)
                                        {
                                             0x00                                             // .
                                        })
                                    }

                                }
                            }
                            Case (One)
                            {
                                Return (One)
                            }
                            Default
                            {
                                Return (Zero)
                            }

                        }
                    }
                    Else
                    {
                        Return (Buffer (One)
                        {
                             0x00                                             // .
                        })
                    }
                }
            }
        }

> what do I do? Ive gotten keyboard to work and it boots fine. (monterrey) Ive tried using the guide at https://github.com/VoodooI2C/VoodooI2C/blob/master/Documentation/GPIO%20Pinning.md but it doesnt seem to match up
Ive also used multiple voodoo kext's and different EFI setups from similiar computers but for the life of me I cannot get it working
attached is my DSDT and current config. Trackpad shows up as Elan0708 in windows device mgr
[DSDT.zip](https://github.com/VoodooI2C/VoodooI2C/files/14825688/DSDT.zip) 
[config.zip](https://github.com/VoodooI2C/VoodooI2C/files/14825697/config.zip)

  `

**Comment by kprinssu** [comment]
This is not a place for requesting help with your configuration. 

Please **_read_** the GitHub issue template.
