### ISSUE TITLE
Can't build on macOS 14.4.1 with Xcode 14.3

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [VoodooI2C/VoodooI2C#548]
Trying to build VoodooI2C on macOS 14.4.1 with Xcode 14.3, I just get the error "/Users/ella/kexts/VoodooI2C/Multitouch Support/VoodooI2CDigitiserTransducer.hpp:12:10 'IOKit/IOLib.h' file not found". Every other kext I've tried building builds fine so I don't think I'm missing anything required to build.

**Comment by kprinssu** [comment]
Please read the documentation on how to build. You are clearly missing MacKernelSDK and probably others.

**Comment by Lost-Entrepreneur439** [comment]
Nope, I have MacKernelSDK and everything else required to build.

**Comment by kprinssu** [comment]
As previously mentioned, support will not be provided. Please use Gitter's developer channel.
