### ISSUE TITLE
Upgrading VoodooI2C / VoodooI2CHID after 2.4.4 causes tearing, glitches on Dell XPS 9500 / 9700 /Precision 5550 / 5750 trackpad

### ISSUE THREAD

**Issue by VGerris** [VoodooI2C/VoodooI2C#549]
**Describe the bug**
After upgrading after 2.4.4 glitches / hopping happens on trackpads on 

https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/issues/7

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system? 
MacOS from about 11 up until 14.4.1
2. What version of the drivers (including drivers) are you using?
2.8 - these have the issues ( 2.4.4 ) do not 
3. What is your hardware configuration?
Dell XPS 9500 / Precision 5550.

latest BIOS, persistent over many versions

**Troubleshooting Archive**
Please attach the troubleshooting archive (as per https://voodooi2c.github.io/#Troubleshooting/Troubleshooting) and any additional logs or videos demonstrating the problem. Please attach any extra files to Github and *not* anywhere else like Google Drive.

**Additional context**
Looks like a change after 2.4.4 that causes this

References :
https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/issues/7

_comment @jkbuha :
 I know that versions 2.5+ try and autodetect the GPIO
pin and may work incorrectly at times, even though my SSDT forces the
APIC pin.

For anyone who's got this issue, it might be worth logging a bug with the
VoodooI2C team together with the log files when the issue happens._

I will gather logs a.s.a.p. and share this link to the other place so hopefully more info can be gathered.
Thank you

**Comment by kprinssu** [comment]
Please re-open after you attached a proper troubleshooting archive.
