### ISSUE TITLE
macOS Sequoia support

### ISSUE THREAD

**Issue by dreamwhite** [VoodooI2C/VoodooI2C#552]
Good morning everyone, I'm opening this issue to keep track of the possible code changes that are required to make VoodooI2C work with the newest release of macOS codename Sequoia.

At the time of writing, VoodooI2C kext v2.8 correctly loads but both in `Interrupt` and `Polling` mode the trackpad doesn't work, totally frozen.

I'm attaching here:

- screenshot of IORegistryExplorer `I2C0.TPD0` device informations:

![voodooi2c sequoia tree](https://github.com/VoodooI2C/VoodooI2C/assets/17933708/892b824d-5b14-4aa1-8ce2-758b077ee13f)

- EFI used (with stripped serial numbers + `-lilubetaall` boot-arg: [EFI](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/tree/master/EFI)

- `AppleIntelLpssI2C` original Sequoia kexts: [AppleIntelLpssI2C.zip](https://github.com/user-attachments/files/15801021/AppleIntelLpssI2C.zip)

Please note that:

1. It's not in my intentions stressing the team
2. with or without `-vi2c-force-polling` boot-arg, the IORegistryExplorer tree of `I2C0.TPD0` is the same as the screenshot
3. in case you need an IORegistryExplorer full dump, is there any ""private"" way of contacting you? I don't wanna spread my serial numbers worldwide :)

Please let me know if you need any other log and additionally how to get them and why not, maybe I can be a tester of new possible versions

Greetings
dreamwhite

**Comment by dreamwhite** [comment]
Seems like VoodooI2C issues got fixed after reading this comment by @1Revenger1 on https://github.com/VoodooI2C/VoodooI2CHID/pull/75#issuecomment-2161297712.

I tested it by replacing the bundled `VoodooInput.kext` inside `VoodooI2C.kext/Contents/Plugins`with [this artifact](https://github.com/1Revenger1/VoodooInput/actions/runs/9475484687) both with and without `-vi2c-force-polling` boot-arg, so I'm pretty sure the fix works.

In any case I'll keep this issue opened unless not needed anymore

**Comment by kprinssu** [comment]
Thanks for the detailed breakdown. We'll need to update VoodooInput with the updated device identifiers.

**Comment by narcyzzo** [comment]
> Seems like VoodooI2C issues got fixed after reading this comment by @1Revenger1 on [VoodooI2C/VoodooI2CHID#75 (comment)](https://github.com/VoodooI2C/VoodooI2CHID/pull/75#issuecomment-2161297712).
> 
> I tested it by replacing the bundled `VoodooInput.kext` inside `VoodooI2C.kext/Contents/Plugins`with [this artifact](https://github.com/1Revenger1/VoodooInput/actions/runs/9475484687) both with and without `-vi2c-force-polling` boot-arg, so I'm pretty sure the fix works.
> 
> In any case I'll keep this issue opened unless not needed anymore

can confirm this works GDX1515 here

**Comment by kprinssu** [comment]
Awesome, thanks for also confirming @narcyzzo

**Comment by jonasw8** [comment]
any news?

**Comment by kprinssu** [comment]
@dreamwhite @narcyzzo  Can you please try https://github.com/VoodooI2C/VoodooI2C/releases/tag/v2.9

It should fix the broken trackpads on macOS 15.

**Comment by AlfCraft07** [comment]
A new problem has arised: the VoodooInput kext is completely broken on macOS 15.2, as a result completely breaking keyboard and trackpad functionality and essentially turning laptops into paperweights. I guess a fix is needed ASAP, even before final release, as the odds are high the problem will remain.

**Comment by kprinssu** [comment]
@AlfCraft07 The original issue that VoodooInput used an older Magic Trackpad identifier that was removed in macOS 15+. Can you please raise further issues upstream with Acidanthera (https://github.com/acidanthera/bugtracker)? 

I will not be providing support for upstream VoodooInput issues.

**Comment by kprinssu** [comment]
I am closing this as resolved. Please re-open this if the issue persists.

**Comment by AlfCraft07** [comment]
> @AlfCraft07 The original issue that VoodooInput used an older Magic Trackpad identifier that was removed in macOS 15+. Can you please raise further issues upstream with Acidanthera (https://github.com/acidanthera/bugtracker)?
> 
> I will not be providing support for upstream VoodooInput issues.

I already opened an issue there, but I haven't got any reply yet.

**Comment by kprinssu** [comment]
@AlfCraft07 Your issue is with VoodooInput and **not a** bugtracker for VoodooInput. Please wait over there for a response.


Please stop spamming here.
