### ISSUE TITLE
kernel panic after voodooi2c installation

### ISSUE THREAD

**Issue by erfan-azari** [VoodooI2C/VoodooI2C#554]
my trackpad on ASUS Vivobook X542UR wasn't working, and macos didn't identify any trackpad or touchpad connected to the laptop.
i tried to add VoodooI2C and VoodooI2CFTE to make trackpad work but that made my system to kernel panic and the error is "can't perform kext scan: no kext summary".
VoodooPS2Controller didn't kernel panic my system but trackpad wasn't even connected.
and also i'm using macos big sur. and there is the [EFI](https://github.com/user-attachments/files/16469846/EFI.zip) that i'm using.

**Comment by kprinssu** [comment]
Please read the Gothub issue template.
