### ISSUE TITLE
Top of Touch screen not working

### ISSUE THREAD

**Issue by rE8007** [VoodooI2C/VoodooI2C#557]
I need help with a touch screen problem on my HP elite x2 g1. All of the multi touch functions work but the top half of my screen doesn't seem to be recognized. I have attached the computer specs as well as a video showing the problem I am having. It works fine with the track pad and I didn't have this issue when windows was installed. Booting with OpenCore 
**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system?  Mac OS Monterery
2. What version of the drivers (including drivers) are you using? 2.8
3. What is your hardware configuration? HP Elite x2 1012 G1
4. Intel Core m5
5. Intel HD Graphics 515 
6. Intel wifi and bluetooth
7. Believe touch screen is wacom

https://github.com/user-attachments/assets/6747c843-fb15-4be8-8b91-77f39466f0d8

![Screen Shot 2024-09-12 at 9 26 31 AM](https://github.com/user-attachments/assets/8ee92f88-cb54-4dd0-8cc8-111eb452434f)

**Comment by kprinssu** [comment]
Closed due to lack of troubleshooting archive.
