### ISSUE TITLE
Magic Trackpad 2 event causing sleep issues!

### ISSUE THREAD

**Issue by ShashwanthN** [VoodooI2C/VoodooI2C#559]
After waking from sleep, the system log reports activity from a "Magic Trackpad 2" device, triggering the system to stay awake. This is unexpected since the only input device is the trackpad integrated into the Hackintosh, and no external Magic Trackpad 2 is connected.

Did you read the common errors documentation?
Yes.

Did you read the troubleshooting documentation?
Yes.

Have you searched the issue on Github, Gitter, or Google?
Yes.

I tried disabling VoodooPS2Controller.kext now kernal panic happens at 00:00:01 instead of 00:00:00 haha

System Environment

Operating System: macOS (Sonoma  14.7 running on Hackintosh)
Driver Versions: Include versions of all relevant drivers, especially VoodooI2C and any other HID-related kexts.
Hardware Configuration:
Processor: Ryzen 5 5500u
Motherboard: Dell inspiron 7415 2 in 1
Input Devices: Integrated trackpad (no external Magic Trackpad)
Troubleshooting Archive
I have attached the troubleshooting archive as specified in the documentation, along with logs from WindowServer showing the unexpected input activity

```
	PID 159(WindowServer) TurnedOn UserIsActive "com.apple.iohideventsystem.queue.tickle serviceID:1000002dc service:AppleMultitouchDevice product:Magic Trackpad 2 eventType:11" 00:00:00  id:0x0x900008035 [System: DeclUser kDisp]          
2024-10-25 23:40:54 +0530 Assertions          	Kernel Idle sleep preventers: IODisplayWrangler 
```

Additional context
The integrated trackpad seems to be generating unintended wake signals as if it were a Magic Trackpad 2. Any adjustments made to config.plist HID or USB settings have not prevented the issue.

**Comment by kprinssu** [comment]
I am closing this due to lack of details. Please read the GitHub issue template.

Additionally, the latest stable version of VoodooI2C *does not* support AMD.
